### ISSUE TITLE
Nuget

### ISSUE THREAD

**Issue by Jetski5822** [Husqvik/GraphQlClientGenerator#1]
Looks sweet - Exactly what I was looking for, fancy putting a preview version on nuget for me? please :)

**Comment by Husqvik** [comment]
https://www.nuget.org/packages/GraphQlClientGenerator/0.1.2

**Comment by DarkWanderer** [comment]
This may be a bit old, but it may be worth putting executable into NuGet as well - as a "tools" package like OpenCover or ILMerge
