### ISSUE TITLE
Newtonsoft.Json errors

### ISSUE THREAD

**Issue by Mrsevic** [Husqvik/GraphQlClientGenerator#103]
Hello, 

I have successfully generated definitions in my project but all over the place I have errors regarding inside the code blocks with GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON?

Is Netwonsoft.Json package necessary for this to work? Is there any command argument where I can disable it?

I have temporarly declared it manually, but even then I get ton of issues like "Cannot convert from System.Type to project_namespace.Type" and "Type does not contain definition for".

Thanks

**Comment by Husqvik** [comment]
Netwonsoft.Json is not core required but its support provides additional functionality for dynamic types. The `GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON` directive is defined exactly for this purpose. If you want to use the generated code without Netwonsoft.Json dependency, you must `#define GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON` without your project.

**Comment by Mrsevic** [comment]
Thanks a lot @Husqvik for swift response. 

I've imported Netwtonsoft.Json 13.0.1 dependency, however the problem is that I then have the following messages:
"GraphQlInterfaceJsonConverter" does not implement inherited abstract member JsonConverter.CanConvert(Type)

All usual "Cannot convert from System.Type to project_namespace.Type" remain.

**Comment by Husqvik** [comment]
are you sure you refer the right type? JsonConverter is in both System.Text.Json.Serialization and Newtonsoft.Json namespaces.

**Comment by Mrsevic** [comment]
These are the namespaces that are included:
// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Linq;
using System.Reflection;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
#endif

namespace _project_namespace_.Generator

In regards to the line of code refers to "Cannot convert from System.Type to project_namespace.Type" error:
Most are coming from ReverseMapping method but also from the builder classes such in this case:
 private static readonly FieldMetadata[] AllFieldMetadata =
{
            new FieldMetadata { Name = "accessToken", IsComplex = true, QueryBuilderType = typeof(AccessTokenDtoQueryBuilder) }

**Comment by Husqvik** [comment]
there must be `{` after namespace. which is not in your example. Can you post the entire file generated. Maybe the schema too so I can generate it myself.

**Comment by Mrsevic** [comment]
Hey,

There's a namespace I've simply not included it.

Unfortunately it is a 3rd party project so I cannot do it. Will try to see if I can somehow replace the names of the variables.

Maybe it's due to the version 10 of hot chocolate that I am using.

Will let you know as soon as possible.

Thanks again for you readiness to help

**Comment by Mrsevic** [comment]
Upon further inspections there was a enum **Type** declared in my solution which was subsequently in the collision with the **System.Type**.

Thanks for your help, I'll close this one now.
