### ISSUE TITLE
External json files cannot be included in a project with GraphQlClientGenerator lib installed

### ISSUE THREAD

**Issue by iocio005** [Husqvik/GraphQlClientGenerator#104]
Hello,

I've included an external json file with configuration for my project.
When I try to compile, I received following error:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	GRAPHQLGEN1001	Unable to cast object of type 'Microsoft.CodeAnalysis.CSharp.Syntax.QualifiedNameSyntax' to type 'Microsoft.CodeAnalysis.CSharp.Syntax.IdentifierNameSyntax'.	file1	C:\Workroot\example\src\project\CSC	1	
```

I've included that file adding in CSPROJ following line:

```
<ItemGroup>
    <AdditionalFiles Include="$(SolutionDir)\stylecop.json" />
</ItemGroup>
```

Installed version is **"GraphQlClientGenerator" Version="0.9.5**

I imagine there is a conflict between library and json file. How can I say to the lib to exclude that file for their purposes?

**Comment by Husqvik** [comment]
Yeah right now the source generate assumes that all additional JSON files are schema files (except `RegexScalarFieldTypeMappingProviderConfiguration.json`). I can change it to match only `*.gql.schema.json`, how about that?

**Comment by iocio005** [comment]
I think that could be a good approach. Thanks for your soon response. When do you think that could be available? Let me know please, thank you!

Best regards.

**Comment by Husqvik** [comment]
https://www.nuget.org/packages/GraphQlClientGenerator/0.9.8
