### ISSUE TITLE
Error CS0616: 'GraphQlObjectTypeAttribute' is not an attribute class (CS0616)

### ISSUE THREAD

**Issue by dori4n** [Husqvik/GraphQlClientGenerator#107]
If the GraphQL schema defines an object type with name `attribute` or `Attribute` a name collision occurs, such that the `GraphQlObjectTypeAttribute` class in the generated code inherits from the local class object instead of `System.Attribute`.

It's an easy fix. Simply make the [the `GraphQlObjectTypeAttribute` class](https://github.com/Husqvik/GraphQlClientGenerator/search?q=GraphQlObjectTypeAttribute) inherit from the fully qualified namespace like
```csharp
public class GraphQlObjectTypeAttribute : System.Attribute
{
    public string TypeName { get; }

    public GraphQlObjectTypeAttribute(string typeName) => TypeName = typeName;
}
```

**Comment by Husqvik** [comment]
It is attribute class. It's used to define the concrete classes implementing a GraphQl interface. If you have any field defined as interface type a concrete type returned by the GraphQL server must be resolved based on the resulting JSON. It's a helper class to achieve that. So if your API doesn't have any interfaces that attribute is never used.

**Comment by dori4n** [comment]
Not what I meant.
I have a class called `Attribute` and a collection called `Attributes` *in the GraphQL API I am using*.
This results in a local class called `Attribute` to be generated. Local classes take precedence over any imported ones from a `using` statement. This means, the local `Attribute` class will override the import of `System.Attribute` from the `System` namespace, which means **attributes stop working**.

This is a bug and needs fixing.
Actually, you can expand this bug further: You are not checking for any type conflicts anywhere at all.
