### ISSUE TITLE
C# 9 source generator custom types not working anymore

### ISSUE THREAD

**Issue by PaulP92** [Husqvik/GraphQlClientGenerator#109]
With version 0.9.10 the custom types provided by RegexScalarFieldTypeMappingProvider.gql.config.json not working.

The type mapping provider configuration file constant ends with ".gql.config.json"
https://github.com/Husqvik/GraphQlClientGenerator/blob/4c5a82787659be153b9ce5debb47ed649d54e2ab/src/GraphQlClientGenerator/GraphQlClientSourceGenerator.cs#L15

The source generator is looking for schema files ending with ".gql.schema.json" 
https://github.com/Husqvik/GraphQlClientGenerator/blob/4c5a82787659be153b9ce5debb47ed649d54e2ab/src/GraphQlClientGenerator/GraphQlClientSourceGenerator.cs#L43

So the index of the type mapping provider configuration file will always be -1
https://github.com/Husqvik/GraphQlClientGenerator/blob/4c5a82787659be153b9ce5debb47ed649d54e2ab/src/GraphQlClientGenerator/GraphQlClientSourceGenerator.cs#L44-L45

Can you fix this?

Thank you for your great work.

**Comment by Husqvik** [comment]
Yeah, I'll will. Sorry of inconvenience, quite busy in my commercial projects ATM.

**Comment by Husqvik** [comment]
https://www.nuget.org/packages/GraphQlClientGenerator/0.9.11

**Comment by PaulP92** [comment]
Thank you, its working
