### ISSUE TITLE
Invalid variable name in AddArgument for directive

### ISSUE THREAD

**Issue by agenceplus-emillon** [Husqvik/GraphQlClientGenerator#110]
I have this code generated:
```csharp
    public class AwsCognitoUserPoolsDirective : GraphQlDirective
    {
        public AwsCognitoUserPoolsDirective(QueryBuilderParameter<IEnumerable<string>> cognitoGroups = null) : base("aws_cognito_user_pools")
        {
            AddArgument("cognito_groups", cognito_groups);
        }
    }
```
It has generated cognito_groups instead of cognitoGroups.

```
graphql-client-generator --version
0.9.10
```

**Comment by Husqvik** [comment]
corresponds with https://aws.amazon.com/blogs/mobile/graphql-security-appsync-amplify/
`cognito_groups` is correct directive name

**Comment by agenceplus-emillon** [comment]
Yes, it's correct directive name, but the code can't build because the parameter is "cognitoGroups", this should generate
```csharp
AddArgument("cognito_groups", cognitoGroups);
```
or change the parameter name of
```csharp
QueryBuilderParameter<IEnumerable<string>> cognitoGroups = null
```

**Comment by Husqvik** [comment]
sorry, I was mislead that the issues is in the generated GQL, not C#. New packages are uploaded now.

**Comment by agenceplus-emillon** [comment]
Thanks for your work, it's of great help.
Sorry to have mislead you. 

I will maybe make a fork to add the option to only generate data classes and enums.
