### ISSUE TITLE
Empty mutation request when using queryBuilder without values

### ISSUE THREAD

**Issue by exedary** [Husqvik/GraphQlClientGenerator#114]
When building mutation, and there is no any values to retrun specified mutation is empty.
Example: 
```
var request = new MutationQueryBuilder()
            .WithCreateJob(
                new JobQueryBuilder(),
                input)
            .Build();
 ```
Returns "mutation{{}}"

**Comment by Husqvik** [comment]
Could you provide the GraphQL metadata and how the mutation should look like?

**Comment by exedary** [comment]
[metadata.txt](https://github.com/Husqvik/GraphQlClientGenerator/files/9927640/metadata.txt)

**Comment by exedary** [comment]
sry, github does not allow to upload in json format

**Comment by exedary** [comment]
Any updates?

**Comment by Husqvik** [comment]
There are two issues with your query
```csharp
var request =
        new MutationQueryBuilder()
            .WithCreateJob(
                new JobQueryBuilder().WithAllScalarFields(), // you are missing to query at least one field from WithCreateJob mutation, GraphQL doesn't support void mutations
                input /* this is GraphQL parameter reference, OK */)
            .WithParameter(input) // missing - this is GraphQL parameter definition
            .Build()
```

**Comment by exedary** [comment]
Thank you! By the way it works with 
```
var request = new MutationQueryBuilder()
            .WithCreateJob(
                new JobQueryBuilder().WithId(),
                input)
            .Build();
```
I mean without `.WithParameter()`

**Comment by Husqvik** [comment]
Probably depends on the server implementation but it's not valid query without the parameter definition. You should get something like `Variable "$parameterName" is not defined. `
