### ISSUE TITLE
[Feature Request] NullValueHandling when building request

### ISSUE THREAD

**Issue by exedary** [Husqvik/GraphQlClientGenerator#115]
Currently there is no way to ignore null values, i had to add few lines of code to add this behaviour into autogenerated code

**Comment by exedary** [comment]
i am going to make a pull request soon, probably)
But i am not sure about correctness of my realization

**Comment by exedary** [comment]
But currently facing a trouble to force user to pass it like Formatting to Build() Method, probably it's better to pass it as parameter when generating client, idk

**Comment by Husqvik** [comment]
Can you provide more details? Concrete schema and concrete query.
