### ISSUE TITLE
Scalar field with arguments should be treated as complex?

### ISSUE THREAD

**Issue by gao-artur** [Husqvik/GraphQlClientGenerator#121]
Hey, I wonder if this is a bug or by design. Currently, scalars with arguments (like [setState](https://github.com/Husqvik/GraphQlClientGenerator/blob/master/test/GraphQlClientGenerator.Test/TestSchemas/TestSchema2#L5727-L5739) for example) are treated as simple fields and will be added when calling the method `WithAllScalarFields()`. If the argument is not nullable we will get a validation exception from the server. A possible workaround is manually excluding it:
```csharp
new TestThermostatMutationQueryBuilderV1()
    .WithAllScalarFields()
    .ExceptSetState();
``` 
But I think such fields should be marked with `IsComplex = true`

**Comment by Husqvik** [comment]
Good point. Not a bug really as I am aware of this issue, rather wrong design decision :). If we change the logic it changes also the meaning of `WithAllScalarFields` since it's not "all" anymore so we should come with some more appropriate name.

**Comment by gao-artur** [comment]
Maybe this?
```csharp
/// <summary>
/// Include all fields that don't require builder or arguments
/// </summary>
/// <returns>This builder</returns>
public TQueryBuilder WithAllSimpleFields()
{
    IncludeFields(AllFields.Where(f => !f.IsComplex && f.QueryBuilderType == null));
    return (TQueryBuilder)this;
}
```
It's obviously a breaking change. But it can be added as a new method, while the `WithAllScalarFields` can be marked as obsolete with the suggestion to use `WithAllSimpleFields` instead.

**Comment by gao-artur** [comment]
Also, maybe mark the list of scalars (including nested lists) as `IsComplex = false`. Then `WithAllSimpleFields` method will be able to include all fields that don't need any user's input.
