### ISSUE TITLE
Allow self signed certificates

### ISSUE THREAD

**Issue by Logic-Bits** [Husqvik/GraphQlClientGenerator#132]
Hi,

thanks for all the work!

I reimplemented the retreiveSchema Method, because the HttpClient options cant be changed from outside your library.
With .net Core / .net7 there is no way to handle the ssl checks globally.

https://stackoverflow.com/questions/38138952/bypass-invalid-ssl-certificate-in-net-core

You think there is away to customize the httpClient?
Thanks!

**Comment by Husqvik** [comment]
Added an optional `HttpMessageHandler` parameter, just call
```csharp
await GraphQlGenerator.RetrieveSchema(
    HttpMethod.Get,
    "https://api.xxx.com/gql",
    messageHandler: new HttpClientHandler { ServerCertificateCustomValidationCallback = (message, certificate, chain, errors) => true })
```
and the server certificate error should be ignored

**Comment by Logic-Bits** [comment]
Frkn LEGEND! Thx

**Comment by haavamoa** [comment]
How can we bypass this when running dotnet tool @Husqvik ?

**Comment by Husqvik** [comment]
Will need to add an option for it.

**Comment by Husqvik** [comment]
https://www.nuget.org/packages/GraphQlClientGenerator.Tool/0.9.20
