### ISSUE TITLE
CLI Option --includeDeprecatedFields / When is the next release?

### ISSUE THREAD

**Issue by AccsoSG** [Husqvik/GraphQlClientGenerator#133]
I need the CLI option --includeDeprecatedFields. I have seen that this option was already introduced in January with commit 5fb9627. Thanks!

Unfortunately there is no release for this yet. The last release 0.9.14 does not contain this CLI option yet. I wanted to ask when the next release is planned?

**Comment by Husqvik** [comment]
https://www.nuget.org/packages/GraphQlClientGenerator.Tool/0.9.15
