### ISSUE TITLE
__typename should not be checked on empty object

### ISSUE THREAD

**Issue by GarretWayne** [Husqvik/GraphQlClientGenerator#135]
Unfortunately we can get back an empty object and the ReadJson can fail (see image).
![image](https://user-images.githubusercontent.com/47498450/236197176-90129113-ca23-487e-b0fc-a13199c14f93.png)

The solution would be for now to return null when we get an empty object (as the commented out code on line 92).

**Comment by Husqvik** [comment]
Such usage in incorrect. When querying a field that is of an interface type, the query should request `__typename` as it defines which type should be deserialized. You can include it using `.WithTypeName()`. I should probably add an option to generate it. There is even PR for it, https://github.com/Husqvik/GraphQlClientGenerator/pull/125. But not sure of all GraphQL servers always provide it so I'm thinking to make it optional.
