### ISSUE TITLE
Generate Separate Files / Folder Structure

### ISSUE THREAD

**Issue by GarretWayne** [Husqvik/GraphQlClientGenerator#136]
Based on the classes, interfaces and generated regions it would be great to have a separate file structure, so that we can quickly replace the changed code when we regenerate the client. 
This could also lead to a better VSC history, as it won't be a megalithic file.

**Comment by Husqvik** [comment]
that is supported already. Except the hardcoded base classes which is a single resource. But every generated class/enum can be generated as separate file

```
--outputType <OneClassPerFile|SingleFile>                                                      Specifies generated classes organization [default: SingleFile]
```

**Comment by Husqvik** [comment]
you can also override/implement `GenerationContext` and write your own custom structure.
