### ISSUE TITLE
UUID Not Getting Mapped to System.Guid

### ISSUE THREAD

**Issue by adamfisher** [Husqvik/GraphQlClientGenerator#139]
This schema definition below generates out `QueryBuilderParameter<ICollection<object>?>? UserIds` for the **userIds:** parameter but I was expected a GUID. Based on #53 it sounds like UUID would already be supported and automatically convert to a C# GUID?

```graphql
input UserFilterInputType {
  userIds: [UUID!]
  organizationId: Long
}
```

I added a `TypeMappingProvider.gql.config.json` file and linked it in the csproj:

```xml
<AdditionalFiles Include="TypeMappingProvider.gql.config.json" />
```

I added this in the contents of the file:

```xml
[
  {
    "FieldType": "Guid",
    "RegexPattern": "System.Guid"
  }
]
```

Am I just missing something with the config to get this working?

**Comment by Husqvik** [comment]
```json
[
  {
    "patternBaseType": ".+",
    "patternValueType": "^UUID$",
    "patternValueName": ".+",
    "netTypeName": "Guid"
  }
]
```

**Comment by adamfisher** [comment]
Thank you!
