### ISSUE TITLE
Class Mappings not Picking up Renames

### ISSUE THREAD

**Issue by adamfisher** [Husqvik/GraphQlClientGenerator#140]
I have a type defined in the schema like this:

```graphql
type Query {
  users(filter: UserFilterInputType): [UserProfileView!]!
  organizations(
    filter: OrganizationFilterInputType!
  ): [OrganizationProfileView!]!
}
```

But when I generate against it, the builder ends up being called `QueryQueryBuilder` and I'd like this to be called `CoreQueryBuilder`.

I tried variations of the below class mapping in the csproj file but nothing gets picked up when I rebuild (regenerate) the project:

```xml
<GraphQlClientGenerator_CustomClassMapping>Query:Core|QueryQuery:Core</GraphQlClientGenerator_CustomClassMapping>
```

Am I just missing something with the config to get this working?

**Comment by Husqvik** [comment]
Did you include
```
<ItemGroup>
 <CompilerVisibleProperty Include="GraphQlClientGenerator_CustomClassMapping" />
</ItemGroup>
```

in the project file?

**Comment by adamfisher** [comment]
I new it was gonna be something simple. Yep I was missing that property. Thank you for the tip!
