### ISSUE TITLE
Type 'DisplayableErrorQueryBuilder' already defines a member called 'WithProductVariantsBulkUpdateUserErrorFragment' with the same parameter types

### ISSUE THREAD

**Issue by daef** [Husqvik/GraphQlClientGenerator#141]
When I generate the client for shopify (their schema can be found [here](https://shopify.dev/docs/api/admin-graphql/2023-07/objects/queryroot) ) the method WithProductVariantsBulkUpdateUserErrorFragment gets generated twice. It works when I remove one of the two identical implementations, but it's irritating to have to manually edit that 120k likes file after each update.

Any ideas how I could avoid this problem?

**Comment by Husqvik** [comment]
Hi. I assume I would have to create account to access the metadata. Could you store the JSON somewhere and provide link? So I can use it for testing.

**Comment by daef** [comment]
how can i save the json?

**Comment by Husqvik** [comment]
It's actually a GrapQL query that the generator queries the API to get the metadata:

```gql
query IntrospectionQuery {
    __schema {
      queryType { name }
      mutationType { name }
      subscriptionType { name }
      types {
        ...FullType
      }
      directives {
        name
        description
        locations
        args {
          ...InputValue
        }
      }
    }
  }

  fragment FullType on __Type {
    kind
    name
    description
    fields(includeDeprecated: true) {
      name
      description
      args {
        ...InputValue
      }
      type {
        ...TypeRef
      }
      isDeprecated
      deprecationReason
    }
    inputFields {
      ...InputValue
    }
    interfaces {
      ...TypeRef
    }
    enumValues(includeDeprecated: true) {
      name
      description
      isDeprecated
      deprecationReason
    }
    possibleTypes {
      ...TypeRef
    }
  }

  fragment InputValue on __InputValue {
    name
    description
    type { ...TypeRef }
    defaultValue
  }

  fragment TypeRef on __Type {
    kind
    name
    ofType {
      kind
      name
      ofType {
        kind
        name
        ofType {
          kind
          name
            ofType {
            kind
            name
            ofType {
              kind
              name
              ofType {
                kind
                name
              }
            }
          }
        }
      }
    }
  }
```

**Comment by daef** [comment]
With the query at hand it's easy :)
[schema.json.txt](https://github.com/Husqvik/GraphQlClientGenerator/files/12206715/schema.json.txt)

Why not add a --export-schema-json to the tool?

**Comment by Husqvik** [comment]
Pushed new package versions.

>Why not add a --export-schema-json to the tool?

The tool is generator primarily. And even though it includes fetching of the metadata I don't think it should be its scope.
