### ISSUE TITLE
Skip generation of base classes.

### ISSUE THREAD

**Issue by rfriend-zilo** [Husqvik/GraphQlClientGenerator#143]
I would like to separate out the base classes, such as GraphQlQueryParameter.
Because I would like to create some extension methods I can package up and reuse across multiple client libraries within our organization that follow standard paradigms for things like sorting, paging, filtering etc..

For example, I would do something like this in my shared lib

```
public static TBuilder WithOffsetPaging<T>(this T builder, OffsetPaging paging)
    where T : GraphQlQueryBuilder
{
    return builder
        .WithParameter(new GraphQlQueryParameter<int>(KnownGraphParams.Skip, GraphQlTypes.Int, paging.GetSkipValue()))
        .WithParameter(new GraphQlQueryParameter<int>(KnownGraphParams.Take, GraphQlTypes.Int, paging.GetTakeValue()));
}
```

But I've no way to centralize the base classes into my library, and have the generated code use those instead of repeating them in each client library - any suggestions?

**Comment by Husqvik** [comment]
How did you resolve the issue?
