### ISSUE TITLE
Convert model-generated value types from bigint to .NET type long

### ISSUE THREAD

**Issue by adamfisher** [Husqvik/GraphQlClientGenerator#144]
I have a field in my schema defined like below:

```json
  {
    "ObjectType": "V ",
    "ObjectId": 202796130,
    "SchemaName": "mqs",
    "TableName": "OrgView",
    "ColumnName": "OrganizationId",
    "TypeName": "bigint",
    "ColumnId": 1,
    "SystemTypeId": 127,
    "UserTypeId": 127,
    "MaxLength": 8,
    "Precision": 19,
    "Scale": 0,
    "CollationName": null,
    "IsNullable": "0",
    "IsAnsiPadded": "0",
    "IsIdentity": "0",
    "IsComputed": "0"
  },
```

This gets generated out as `public object? OrganizationId { get; set; }` but should really probably be a `long` based on the origin value type. When I add a custom mapping to the regex config I can't get it to generate out. Maybe I have the pattern wrong?

```json
{
    "patternBaseType": ".+",
    "patternValueType": "^bigint$",
    "patternValueName": ".+",
    "netTypeName": "long"
  },
```

**Comment by Husqvik** [comment]
Important is the type name in GraphQL schema. Can you check it's really `bigint` there?
Which method do you use for generation, CLI or source generator?
