### ISSUE TITLE
Non-nullables and nullables mapping

### ISSUE THREAD

**Issue by ErlingMK** [Husqvik/GraphQlClientGenerator#146]
Hi! Love this package! I do have a question about usage that I cannot figure out or maybe have misunderstood. 

With a type like this:

```
    type Visit {
      id: Long!
      startTime: DateTime
      completedTime: DateTime
      levelOfCare: LevelOfCare!
      hospital: Hospital
      department: Department
      section: Section
      ward: Ward
      periodOfCare: PeriodOfCare!
      status: VisitStatus
      detailedLevelOfCareId: Long
      detailedLevelOfCareName: String
    }
```

I expected it to resolve to something like this

```csharp
    public partial class Visit
    {
        public long Id { get; set; }
        public DateTime? StartTime { get; set; }
        public DateTime? CompletedTime { get; set; }
        public LevelOfCare LevelOfCare { get; set; } <-- as an example, this should not be nullable
        public Hospital? Hospital { get; set; }
        public Department? Department { get; set; }
        public Section? Section { get; set; }
        public Ward? Ward { get; set; }
        public PeriodOfCare PeriodOfCare { get; set; }
        public VisitStatus? Status { get; set; }
        public long? DetailedLevelOfCareId { get; set; }
        public string? DetailedLevelOfCareName { get; set; }
    }
```

where `!` maps to non-nullable objects.

But it actually maps to:

```csharp
    public partial class Visit
    {
        public long Id { get; set; }
        public DateTime? StartTime { get; set; }
        public DateTime? CompletedTime { get; set; }
        public LevelOfCare? LevelOfCare { get; set; } <-- as an example, this is nullable
        public Hospital Hospital { get; set; }
        public Department Department { get; set; } <-- as an example, this should be nullable
        public Section Section { get; set; } <-- as an example, this should be nullable
        public Ward Ward { get; set; } <-- as an example, this should be nullable
        public PeriodOfCare PeriodOfCare { get; set; }
        public VisitStatus? Status { get; set; }
        public long? DetailedLevelOfCareId { get; set; }
        public string DetailedLevelOfCareName { get; set; }
    }
```

Is there some configuration for this type of behavior?

**Comment by Husqvik** [comment]
Hi. The reason why the properties are generated nullable in data classes is because even though GraphQL server ensures a value is returned you can still make a query that doesn't request this field at all and using the same data class. In that case it would have been populated with default value which would be misleading.

But I agree if you always query for scalar type value then the nullability is overhead and a bit annoying. There is no configuration for that at the moment, the nullability can potentially removed by implementing own `IScalarFieldTypeMappingProvider`.

**Comment by ErlingMK** [comment]
Ahh, I get it. Makes sense. Thank you for the quick response!

**Comment by Husqvik** [comment]
@ErlingMK added new option that makes the data classes to respect GraphQL schema nullability. It's `AlwaysNullable` by default to ensure backwards compatibility. Can you test it for your case before I build a new package version.
