### ISSUE TITLE
OutputType option is not considered for C# 9 source generator

### ISSUE THREAD

**Issue by SlyCedix** [Husqvik/GraphQlClientGenerator#150]
C# 9 source generator is always generated as a single file, this isn't a huge problem, however if `EmitCompilerGeneratedFiles` is enabled, the file will be output as a single file, making browsing them for debugging purposes much more difficult.

IDEs get real angry about loading a 120k+ line source file

**Comment by Husqvik** [comment]
Fixed in https://github.com/Husqvik/GraphQlClientGenerator/commit/fd03ee5fa8dc4866c8c9b5026a35dbb68a6c77b1
