### ISSUE TITLE
[Feature Request] Add `__typename` to generated classes

### ISSUE THREAD

**Issue by kaioduarte** [Husqvik/GraphQlClientGenerator#151]
It would be great if the generated classes had the `__typename` field, which is needed when dealing with unions.

**Comment by gao-artur** [comment]
Alternatively, there is a proposal (2) in the #126. For example, for the union called `Assignee` with two entries: `Team` and `Employee` generate an empty interface `IAssignee` and "implement" it on the `Team` and `Employee` classes. Then, the user can use pattern matching to find out what the real type behind the union. For example
```c#
public interface IAssignee { }

public class Team : IAssignee
{
    public string Name { get; set; }
}

public class Employee : IAssignee
{
    public string FullName { get; set; }
}
```

Usage:
```c#
var assignee = QueryAssignee();
var greeting = assignee switch
{
    Team team => $"Hello {team.Name}!",
    Employee employee => $"Hello {employee.FullName}!",
    _ => throw new ArgumentException($"Unexpected assignee type {assignee.GetType().Name}", nameof(assignee))
};
```

**Comment by Husqvik** [comment]
I think it should deserialize into appropriate type just as interfaces do.
