### ISSUE TITLE
DataClassMemberNullability option not respected in csproj definition.

### ISSUE THREAD

**Issue by Blightbuster** [Husqvik/GraphQlClientGenerator#160]
Hey, I believe that when adding the DataClassMemberNullability option  (https://github.com/Husqvik/GraphQlClientGenerator/issues/146#issuecomment-1801957022), it was not implemented to read its value from the csproj file.

Adding the following line to my project file did infact not use the schema defined nullability.
```xml
<GraphQlClientGenerator_DataClassMemberNullability>DefinedBySchema</GraphQlClientGenerator_DataClassMemberNullability>
```

Neither could I locate any point in the [Execute(...)](https://github.com/Husqvik/GraphQlClientGenerator/blob/8b2037c39116feaf954d3b89ed9ec2339074b23b/src/GraphQlClientGenerator/GraphQlClientSourceGenerator.cs#L25C1-L25C5) method where it reads this setting.

**Comment by Husqvik** [comment]
https://www.nuget.org/packages/GraphQlClientGenerator/0.9.22
