### ISSUE TITLE
Suggestion: add sorting in GraphQlGenerator.cs

### ISSUE THREAD

**Issue by VusalDev** [Husqvik/GraphQlClientGenerator#162]
Each use of the generator for the Federation schema produces models with identical content but different ordering, making it difficult to track changes through GIT diff.
I attempted to submit a PR, but all tests failed due to slight changes in the sorting order.

![image](https://github.com/user-attachments/assets/11da75df-84a7-48e5-a5e9-e7c313f110ab)

**Comment by Husqvik** [comment]
RIght now the order is given by the JSON metadata provided. Is the ordering indeterminate for all members? Enums, query builders, input object and data classes or only the enums?

**Comment by VusalDev** [comment]
I have done some research, the results are provided in the table.
**ReGeneration** column is the ability of the code block not to change during the generator usage.

| **Code block** | **ReGeneration** | **Sorting** |
|--------|--------|
| `#region base classes` | stable | unsorted  |
| `#region GraphQL type helpers` | stable | sorted |
| `#region enums` | unstable | unsorted |
| `#region directives` | stable | unstorted |
| `#region builder classes` | unstable | unsorted |
| `#region input classes` | unstable | unsorted |
| `#region data classes` | unstable | unsorted |

**Comment by Husqvik** [comment]
Added `build_property.GraphQlClientGenerator_GenerationOrder` / `GraphQlGeneratorConfiguration.GenerationOrder` / `--generationOrder Alphabetical` options, whichever way you use to generate.

**Comment by VusalDev** [comment]
Thank you very much, works as expected.

**Comment by Husqvik** [comment]
Cool, I make a new package version then.

**Comment by Husqvik** [comment]
https://www.nuget.org/packages/GraphQlClientGenerator/0.9.24
