### ISSUE TITLE
Datetime argument 

### ISSUE THREAD

**Issue by CyrilleFormont** [Husqvik/GraphQlClientGenerator#20]
Hi,
I'm facing an issue while using datetime as argument of a query

I'm using the configuration in order to set-up the data type. So my query is well waiting for a DateTime as a parameter of the QueryBuilder.

But once I build my query, here is the result

`diaries (startDate: 06/26/2019 19:10:00, endDate: 06/26/2019 19:10:00) {`

Quotes are missing.

I assume that is because within the "BuildArgumentValue" method in case of DateTime it should return something like 
`return $"\"{argumentValue}\"";`

Do I miss a configuration step here ?

**Comment by Husqvik** [comment]
Good catch, also added deterministic format - ISO8601. And invariant culture for all `IConvertible` types.

Fixed in https://github.com/Husqvik/GraphQlClientGenerator/commit/714bbb7c0cfb329f99da8185540ac1f305c8e320
