### ISSUE TITLE
codegen of complex interfaces needing generic has an issue

### ISSUE THREAD

**Issue by amazdehmtl** [Husqvik/GraphQlClientGenerator#33]
Hi
Thanks for the code. There is an issue which i thought i should mention.
If i have something like

``` csharp

interface Node
{
}

interface NodeCollection
{
Node[] GetNodes();
}

class NetNode : NodeCollection
{
 public NetNode[] GetNodes(){//impl}
}
```

Then the interface generated should be like 

``` csharp

interface NodeCollection<T> where T : Node
{
Node[] GetNodes();
}
```

Currently the interface generated is like the one above rather than this one

**Comment by Husqvik** [comment]
I guess you mean

```interface NodeCollection<T> where T : Node
{
T[] GetNodes();
}```

**Comment by amazdehmtl** [comment]
Maybe yes because in that way you'll not need the analysis. generated code is very verbose in many cases exactly because of this.
If we don't want to do the analysis and see ok an interface seem to be implemented using a type which is not actually exactly the type requested (it is relatively easy to do this in roslyn however)
One way is to make them all generic, another is to load the generated code in roslyn and then execute a linq query to check if any interface implementer is not using exactly the type requested for its parameters/return types and then make that parameter a generic one.

However always generic interfaces for parameters would solve it too at least in our case that was what i did.

**Comment by Husqvik** [comment]
The interfaces should be fully supported now
