### ISSUE TITLE
generated query builders for objects without fields don't compile

### ISSUE THREAD

**Issue by amazdehmtl** [Husqvik/GraphQlClientGenerator#34]
The generated query builders has an WithAll which implements itself by using a new[]{} and this is not a problem when you got fields since inside the initializer list, you have `new MetaField` ... but when without fields. The compiler cannot differ the type so the generated array should explicitly mention its type.

Thanks again for the lib and i might get the time to fix it myself if my boss allows me.

**Comment by Husqvik** [comment]
This case baffles me a little as it has been mentioned many times. What purpose is to have a type without any field?

**Comment by amazdehmtl** [comment]
I don't know honestly speaking, i didn't generate the schema. You can even skip generating the methods for them. 
The way that I'm in our current project is like, i got some free time so our company put me on this to help the guys a bit so I've not been there from the beginning on the designs.

**Comment by carlwoodhouse** [comment]
> This case baffles me a little as it has been mentioned many times. What purpose is to have a type without any field?

happens for me when it trys to generate a union

**Comment by Husqvik** [comment]
Yeah people mentioned union, I guess it could be because it just "union" multiple existing types into one and not defining own fields on its own. If I can get some example schema containing it I could decide if it's just fine to ignore those or if there should be generated another kind of class to model it.

**Comment by carlwoodhouse** [comment]
i mean yeah, thats pretty much it (union existing types, non of its own fields)

ala ..

![image](https://user-images.githubusercontent.com/465424/68435985-a3149e80-01b4-11ea-8ec3-7c1b0bf834bb.png)

**Comment by carlwoodhouse** [comment]
i mean it should possibly be modelling something that does `possibleTypes`

**Comment by Husqvik** [comment]
Ok added skipping of generating data entities without fields. Another option for an UNION would be to generate a class containing all fields of the union-ed classes.
