### ISSUE TITLE
Calling WithAllFields throws StackOverflowException

### ISSUE THREAD

**Issue by amazdehmtl** [Husqvik/GraphQlClientGenerator#35]
Calling all fields in
```
QueryQueryBuilder().WithAllFields().Build();
```

Throws the exceptions and the methods go to infinite recursion.

Are we supposed to call it in a special way or on special objects? or this is a bug. Also calling it from my top level queries has the same result too.

Lower level objects closer to the liefs seem to be fine and WithAllSclaerFields is fine.

**Comment by Husqvik** [comment]
Currently there is no check for recursive query fields. So you have to specify such fields manually. `WithAllFields` method is mostly meant for simple cases when the child data hierarchy is not big and the queries fields do not require any obligatory parameters.

**Comment by amazdehmtl** [comment]
Thanks
