### ISSUE TITLE
Query builder doesn't provide option for alias names

### ISSUE THREAD

**Issue by sarvabowmen** [Husqvik/GraphQlClientGenerator#36]
For ex:
{
A: schema1{
name
id
schema1Value: value
},
B: schema2{
name
id
schema2Value: value
}
}

**Comment by sarvabowmen** [comment]
I have a fix for it, happy if you are accepting PR's

**Comment by Husqvik** [comment]
I wasn't aware of that feature :). I accept PR but I doubt it would be proper implementation as the alias is dynamic value that can be mapped to any property (so it's impossible to know it at compile time). But it interesting issue so I try to make something about it.

**Comment by sarvabowmen** [comment]
Yeah it is a dynamic value, The library should allow the client to define a custom name for scalar variables and also provide options to create multiple queries just to avoid a separate call

Ex: 1
If I want a specific property with a specific name, I can use an alias against that scalar property

```
MyQuery {
orders(first:10)
{
orderName: name,
orderid: id
}
}
```

Because I can map it to the response models, which i already name with the same name.

Ex2:  
Execute Multiple queries in the same batch

```
MyQuery {
A: schema1{
name
id
schema1Value: value
},
B: schema2{
name
id
schema2Value: value
}
}
```

**Comment by Husqvik** [comment]
Last version fixes that. You can utilize aliases like

```csharp
new ViewerQueryBuilder()
	.WithHome(
		new HomeQueryBuilder("primaryHome")
			.WithType()
			.WithSize()
			.WithAddress(new AddressQueryBuilder("primaryAddress").WithAddress1("primaryAddressText").WithCountry()),
		Guid.NewGuid())
	.WithHome(
		new HomeQueryBuilder("secondaryHome")
			.WithType()
			.WithSize()
			.WithAddress(new AddressQueryBuilder("secondaryAddress").WithAddress1("secondaryAddressText").WithCountry()),
		Guid.NewGuid())
	.Build(Formatting.Indented)
```

generated query:

```
{
  primaryHome: home (id: "70ae8630-5db4-44f6-a7da-5fc96329b9d2") {
    type
    size
    primaryAddress: address {
      primaryAddressText: address1
      country
    }
  }
  secondaryHome: home (id: "3a7c274d-17ff-402f-b22c-1aab4101cef8") {
    type
    size
    secondaryAddress: address {
      secondaryAddressText: address1
      country
    }
  }
}
```
