### ISSUE TITLE
Variable support

### ISSUE THREAD

**Issue by timjk** [Husqvik/GraphQlClientGenerator#37]
A common graphql use-case is to use variables in queries & mutations https://graphql.org/learn/queries/#variables.

Variable support could look like:

### Query:
- Accept a variable type in `WithX` methods
  - could have a variable name as a constructor parameter or a builder method etc...

```csharp
var builder =
  new QueryQueryBuilder()
    .WithMe(
      new MeQueryBuilder()
        .WithAllScalarFields()
        .WithHome(
          new HomeQueryBuilder()
            .WithAllScalarFields()
            .WithSubscription(
              new SubscriptionQueryBuilder()
                .WithStatus()
                .WithValidFrom())
            .WithSignupStatus(
              new SignupStatusQueryBuilder().WithAllFields())
            .WithDisaggregation(
              new DisaggregationQueryBuilder().WithAllFields()),
          new Variable<Id>("b420001d-189b-44c0-a3d5-d62452bfdd42", "homeId"))
        .WithEnergyStatements (new Variable<string>("2016-06", "from"), new Variable<string>("2016-10", "to"));

var query = builder.Build(Formatting.Indented);
```
Results into

```
{
query: "query ($homeId: Id, $from: string, $to: string) {
  me {
    id
    firstName
    lastName
    fullName
    ssn
    email
    language
    tone
    home (id: $homeId) {
      id
      avatar
      timeZone
      subscription {
        status
        validFrom
      }
      signupStatus {
        registrationStartedTimestamp
        registrationCompleted
        registrationCompletedTimestamp
        checkCurrentSupplierPassed
        supplierSwitchConfirmationPassed
        startDatePassed
        firstReadingReceived
        firstBillingDone
        firstBillingTimestamp
      }
      disaggregation {
        year
        month
        fixedConsumptionKwh
        fixedConsumptionKwhPercent
        heatingConsumptionKwh
        heatingConsumptionKwhPercent
        behaviorConsumptionKwh
        behaviorConsumptionKwhPercent
      }
    }
    energyStatements(from: $from, to: $to) 
  }",
  variables: {
    homeId: "b420001d-189b-44c0-a3d5-d62452bfdd42",
    from: "2016-06",
    to: "2016-10"
  }
}
```
### Mutation

```csharp
var mutation =
	new RootMutationQueryBuilder()
		.WithUpdateHome(
			new HomeQueryBuilder().WithAllScalarFields(),
			new Variable<UnpdateHomeInput>(new UpdateHomeInput { HomeId = Guid.Empty, AppNickname = "My nickname", Type = HomeType.House, NumberOfResidents = 4, Size = 160, AppAvatar = HomeAvatar.Floorhouse1, PrimaryHeatingSource = HeatingSource.Electricity }, "homeInput")
		)
	.Build(Formatting.Indented, 2);
```
Results into
```
{
query: "mutation ($homeInput: UpdateHomeInput!) {
  updateHome (input: $homeInput) {
    id
    timeZone
    appNickname
    appAvatar
    size
    type
    numberOfResidents
    primaryHeatingSource
    hasVentilationSystem
  }
}",
variables: {
  homeInput: {
      homeId: "00000000-0000-0000-0000-000000000000"
      appNickname: "My nickname"
      appAvatar: FLOORHOUSE1
      size: 160
      type: HOUSE
      numberOfResidents: 4
      primaryHeatingSource: ELECTRICITY
    }
}
```

Could extend it further and generate the query and variables separately which would allow you to statically use the same query and dynamically generate the variables per request

```csharp
var builder =
	new RootMutationQueryBuilder()
		.WithUpdateHome(
			new HomeQueryBuilder().WithAllScalarFields(),
			new Variable<UnpdateHomeInput>("homeInput")
		);

var mutation = builder.Build(Formatting.Indented, 2);
var variables = builder.BuildVariables(...) // Would have to do something clever with types here...
```

**Comment by Husqvik** [comment]
I would say the variables are just convenience for manually written queries not to repeat the same id at many places. You still have to explicitly mark every place the parameter is used which makes no difference to actually set that parameter explicitly. So you can easily define your extension method that builds the query using parameters that are set to all needed places but you would pass them just once as the parameters of the extension method.

**Comment by Husqvik** [comment]
```csharp
var input = new UpdateHomeInput { HomeId = Guid.Empty, AppNickname = "My nickname", Type = HomeType.House, NumberOfResidents = 4, Size = 160, AppAvatar = HomeAvatar.Floorhouse1, PrimaryHeatingSource = HeatingSource.Electricity };
var parameter = new GraphQlQueryParameter<UpdateHomeInput>("homeInput", nameof(UpdateHomeInput), input);

var mutation =
	new TibberMutationQueryBuilder()
		.WithUpdateHome(
			new HomeQueryBuilder().WithAllScalarFields(),
			parameter
		)
	.WithParameter(parameter)
	.Build(Formatting.Indented, 2)
```

**Comment by StefanCop** [comment]
I vote for Parameter and Variable support. My GraphQl service chief delevoper wants to register allowed queries and mutation. And they must only contain parameter/variable, otherwise it will be considered as a new, unregistered query. 
My idea is that "where" accept none pimitive type (i.e. Guid?) but QueryBuilderParameter<Guid?>.

            public partial class uuid_comparison_exp
            {
                    public QueryBuilderParameter<Guid?> Eq
                    {
                        get { return (QueryBuilderParameter<Guid?>)_eq.Value; }
                        set { _eq = new InputPropertyInfo { Name = "_eq", Value = value }; }
                    }
            }

and in GraphQlQueryHelper BuildArgumentValue:

            if (value is QueryBuilderParameter parameter)
            {
                if (!string.IsNullOrWhiteSpace(parameter.Name))
                    return "$" + parameter.Name;
                else
                    return BuildArgumentValue(parameter.Value, formatting, level, indentationSize);
            }

**Comment by Husqvik** [comment]
What is the issue with the current solution?

**Comment by StefanCop** [comment]
I need to Build() for example a mutation string like this: 

mutation deleteUsers ($userIds:[uuid!]!) {
    resultDeleted:delete_ums_users(
        **where:{id:{_in:$userIds}}**
    ) {
        affected_rows,
        returning{id}
    }
}

**Comment by Husqvik** [comment]
Ok, finally I think I get it. It's not possible to set dynamic parameter as field of any input object.

I really don't want to introduce complex type properties as I would like to have the input objects properties plain data types.

How about to generate `With{PropertyName}Parameter(QueryBuilderParameter<T>)` where a parameter can be passed?

So the use would be
```csharp
new InputObject
{
    Property1 = constantValueParameter
}
.WithProperty2Parameter(dynamicQueryParameter);
```

Or maybe the query parameter after all as you suggest but securing the JSON serialization works both ways. With just plain values.

**Comment by StefanCop** [comment]
I liked the idea of `QueryBuilderParameter<T>`. This lets me create a `GraphQlQueryParameter<T>`instance and use it for both, its name for the variable name in query/mutation strings, and its value for the GraphQL.Client GraphQLRequest Variable property when called.  

In my schema `T` is not only a simple type but an INPUT_OBJECT structure, i.e. a list of data to insert or update or parameters to query (order by, where clause). I hope, with a few JsonAttribute (for nullable properties) this approach will work with the generated classes for theses INPUT_OBJECTs. 
So I suppose my idea affects basically every `IGraphQlInputObject`, maybe this is too much of change. 

I'll try a prototype on my side and post my findings?

**Comment by Husqvik** [comment]
I made some tests and I believe it works. I'll push the changes soon.

**Comment by StefanCop** [comment]
Great, I'm looking forward! Because the genrator is really what I was looking for, it is great!

**Comment by Husqvik** [comment]
Can you test it out before a I make new Nuget package?

**Comment by StefanCop** [comment]
I made some basic test. There's one correction in ValidateParameterValue. And I have 3 additional Test. Do you want changes as zip or on a git branch?


    private void ValidateParameterValue(string parameterName, string value)
    {
        // Spec says: /[_A-Za-z][_0-9A-Za-z]*/ 
        if (String.IsNullOrWhiteSpace(value) || !value.All(c => Char.IsLetterOrDigit(c) || c == '_'))
            throw new ArgumentException("invalid value", parameterName);
    }

    private void ValidateParameterType(string parameterName, string graphQlTypeName)
    {
        // strip of LIST '[' ']' and NON_NULL '!' for example [me_input!]!
        if (graphQlTypeName.EndsWith("!"))
            graphQlTypeName = graphQlTypeName.Substring(0, graphQlTypeName.Length - 1);
        if (graphQlTypeName.StartsWith("[") && graphQlTypeName.EndsWith("]"))
            graphQlTypeName = graphQlTypeName.Substring(1, graphQlTypeName.Length - 2);
        if (graphQlTypeName.EndsWith("!"))
            graphQlTypeName = graphQlTypeName.Substring(0, graphQlTypeName.Length - 1);
        ValidateParameterValue(parameterName, graphQlTypeName);
    }

**Comment by Husqvik** [comment]
Fixed the identifier validation. Dropped the parameter type, it can get more complex, I might add it later.

```graphql
query Test($values:   [ [ [ ID # coment with /*-@#$%^^&** all the crazy stuff  
 !
 # and more
 ] !  ] ! ] !  ) {
}
```

is acceptable type.

Tests maybe as zip, I was about to extend the compiled assembly tests by the new stuff. Is it that kind of tests or something else?

**Comment by StefanCop** [comment]
[GraphQlClientGenerator.Test.zip](https://github.com/Husqvik/GraphQlClientGenerator/files/4185897/GraphQlClientGenerator.Test.zip)
Not advanced as yours: Generated the TestSchema2.Generated.cs with GraphQlClientGenerator.Console from TestSchema2 ans namespace "GraphQlClientGenerator.TestSchema2", then included it in the test project and wrote three Tests.
