### ISSUE TITLE
Support for Nullable reference types

### ISSUE THREAD

**Issue by bddckr** [Husqvik/GraphQlClientGenerator#38]
Hey there! This is such an awesome project, thanks a lot for creating it and choosing MIT for the license!

I just cloned and ran the console app against our backend and noticed value types are annotated with question marks in the generated types, i.e. they are nullable when the schema says they are.

I'd love to see the same type annotation in the C# types for reference types, thanks to C# 8.0 supporting that. This should probably be an option, as I'm sure not everyone wants to switch to C# 8 for their project just yet 😄 The generated output file should probably enclose the whole source with `#nullable enable` and `#nullable restore` - just in case a user is using C# 8 but not yet turning on nullable ref types for everything.

I am happy to raise a PR for this, but it will be a couple of weeks most likely until I can get to it.

**Comment by Husqvik** [comment]
I'm not sure if I understand. The reason for the nullability for all the fields is because you can query any subset of fields so the data class the result is mapped cannot have not nullable properties because those would be initialized even when you don't query them. Which may lead to unwanted results.

**Comment by bddckr** [comment]
Sorry for the bad description!

What I mean is that for a schema
```graphql
type User {
  id: ID
  name: String
  active: Boolean
}
```

I currently get
```c#
public partial class User
{
    public Guid? Id { get; set; }
    public string Name { get; set; }
    public bool? Active { get; set; }
}
```
while I'd like to get (in C# 8 with nullable reference types):
```c#
public partial class User
{
    public Guid? Id { get; set; }
    public string? Name { get; set; }
    public bool? Active { get; set; }
}
```

Note that the `string Name` changed to `string? Name`. The schema is saying `name: String` after all, not `name: String!`. With this change the nullability annotation in the schema can be fully represented in the generated C# classes.

**Comment by bddckr** [comment]
Oh I'm dumb. I re-read your message and I now see the issue.

Basically _all_ fields are nullable in C# to allow reusing the same type definition, even when a query doesn't ask for those fields.

That makes sense. This issue could be about making sure reference types get the `?` (via a (CLI) option perhaps) then.

**Comment by bddckr** [comment]
Leaving the generated output as is should be fine, as long as the compiler is specifically told that the generated file does not use any new reference type nullability.

If we wrap the generated output in `#nullable disable` and `#nullable restore` the generated output can safely be added to a csproj that uses `<Nullable>enable</Nullable>`. Otherwise the project-wide setting says everything is using `?` for all types whenever they are nullable, which this generated output doesn't.

**Comment by Husqvik** [comment]
Forgot the strings and other reference types. These should be marked with question mark in C# 8 to say explicitly they are nullable. I'll fix that too. Of course with optional setting as it would break compilation for older compiler versions.

**Comment by Husqvik** [comment]
Could you test the changes? I'm pretty sure I missed some spot.

**Comment by bddckr** [comment]
I just updated and ran some of my queries without any problem! All input classes have the proper annotation and are wrapped in `#nullable` (`enable`, then `disable`).

Thanks a lot for the quick changes ❤️
