### ISSUE TITLE
Support "Without" to remove fields

### ISSUE THREAD

**Issue by bddckr** [Husqvik/GraphQlClientGenerator#40]
I hit the same issue as in #35 and while I think this is by design and a wontfix is OK here, I do wonder if there's a point in offering `Except...` methods.

This would allow users to do e.g. `.WithAllFields().ExceptSignupStatus()`. I went with `Except` here [like LINQ uses](https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.except), though typing this out I like `Without` more - it fits the builder pattern better in my opinion.

Something I do *not* like about this is the fact that users could get confused about whether they have to add `Without` calls to their builder to ensure a field is not included. This is the only downsides I was able to come up with, but I didn't check how difficult this is to implement.

Thoughts? :)

**Comment by Husqvik** [comment]
I think in many cases it can be really useful. Not English pro whatsoever but I like the word "except" more than "without". Another option would be "include/exclude" but I kind of like the "with" as it's very short. Also "except" is shorter than "exclude".

I'll include this in the next version. Pretty busy these days but I should find some time.

**Comment by bddckr** [comment]
Include/exclude makes the most sense to me and the use of `With` instead of `Include` seems reasonable as that is what most .NET developers are familiar with when using the builder pattern I believe.

I'm fine with `Except` - it's what LINQ uses and thus should mean it's the most accessible to developers who are new to this library!
