### ISSUE TITLE
Type / field name clashes

### ISSUE THREAD

**Issue by carlwoodhouse** [Husqvik/GraphQlClientGenerator#46]
Currently if a type has a field with the same name as itself; code that wont compile is generated ..

eg.
```
something {
something string
}
```
generates
```
class Something {
string Something
}
```
which results in a compilation error ... not entirely sure if it can be resolved though!

**Comment by Husqvik** [comment]
Last update allows

`GraphQlGeneratorConfiguration.CustomClassNameMapping.Add("something", "SomethingElse");`

which is meant to solve Class/Member name clashes.

**Comment by carlwoodhouse** [comment]
awesome thankyou
