### ISSUE TITLE
CustomClassNameMapping should add Newtonsoft.Json ref to RequiredNamespaces

### ISSUE THREAD

**Issue by carlwoodhouse** [Husqvik/GraphQlClientGenerator#50]
Using `GraphQlGeneratorConfiguration.CustomClassNameMapping.Add` requires Newtonsoft.Json reference due to the use of `JsonProperty` but this isn't added to RequiredNamespaces

**Comment by Husqvik** [comment]
The custom mapping itself is not the reason. The `JsonProperty` attributes are generated when data class property name doesn't match GraphQL member name, for example when GraphQl field "property_name" turns into "PropertyName" property.

But it's the bug for sure. In addition I added configuration options for controlling this in more detail.
