### ISSUE TITLE
Can't create mutation to set input type value to null

### ISSUE THREAD

**Issue by bddckr** [Husqvik/GraphQlClientGenerator#51]
If you have an input type that has a property of type `int?` for example you may want to create a mutation that sets that property to `null`. This is currently not possible due to `null` values being filtered out of input type arguments while building the mutation:
https://github.com/Husqvik/GraphQlClientGenerator/blob/b3fec95ecd801baf452b5fb82da42437447f777e/src/GraphQlClientGenerator/BaseClasses.cs#L118

This schema snippet
```graphql
input TestInput {
  id: ID
  someNullableNumber: Int
}
```
results in this generated C#:
```c#
public class TestInput : IGraphQlInputObject
{
    public string? Id { get; set; }
    public int? SomeNullableNumber { get; set; }
}
```

Just removing that `Where` won't help - it would instead create mutations with null values all the time.

I believe this means we actually need to introduce a wrapper type for any type to allow defining "the value is null" vs. "there is no value". `string??` isn't a thing in C# so maybe a good old `Option` type would do it? E.g.:
```c#
public class TestInput : IGraphQlInputObject
{
    public Option<string?> Id { get; set; }
    public Option<int?> SomeNullableNumber { get; set; }
}
```
This should only be necessary for input types, but it might also be necessary on mutations that are defined to take multiple arguments instead of a single input object. In that case we perhaps need to wrap the arguments into `Option<QueryBuilderParameter<T>>`?

**Comment by Husqvik** [comment]
I tend not to use complex types for public members of just a data class. How about this?

```csharp
public partial class UpdateHomeInput : IGraphQlInputObject
{
	private InputPropertyInfo _homeId;
	private InputPropertyInfo _appNickname;

	public Guid? HomeId
	{
		get => (Guid?)_homeId.Value;
		set => _homeId = new InputPropertyInfo { Name = "homeId", Value = value };
	}

	public string AppNickname
	{
		get => (string)_appNickname.Value;
		set => _appNickname = new InputPropertyInfo { Name = "appNickname", Value = value };
	}

	IEnumerable<InputPropertyInfo> IGraphQlInputObject.GetPropertyValues()
	{
		if (_homeId.Name != null)
			yield return _homeId;

		if (_appNickname.Name != null)
			yield return _appNickname;
	}
}
```

If needed we could generate also `DeleteHomeId()` and `DeleteAppNickname()` methods to remove value once set but I think it isn't necessary as the entire input class would be mostly used only once.

**Comment by bddckr** [comment]
Great idea to move the `InputPropertyInfo` creation into the input type properties! I love keeping the public API as simple as possible.

That will work for me just fine and I also can not see any reason to allow setting it back to "nothing" being set. As you said - they are only used in a create-and-use way.

**Comment by bddckr** [comment]
This does work for me after I also did this, which I raised a PR for: https://github.com/Husqvik/GraphQlClientGenerator/pull/52

If you could merge this and create a new NuGet version right away I can even move over from my own fork to the NuGet package instead ❤️
