### ISSUE TITLE
CustomScalarFieldTypeMapping not working for most builtin types

### ISSUE THREAD

**Issue by groege** [Husqvik/GraphQlClientGenerator#53]
In my case i have a lot of boolean columns that should not be nullable, when deserializing the returned JSON the default value is sufficient.
Therefore I tried CustomScalarFieldTypeMapping but found out that there is no way to make non nullable bool fields actually not nullable => it is hard coded as "bool?", what i want is "bool"

**Comment by Husqvik** [comment]
It was meant only for custom scalar types not for built-in scalar types. I'm going to change it so it will be possible to "override" even the built-in ones.

```csharp
GraphQlGeneratorConfiguration.CustomScalarFieldTypeMapping =
    (baseType, valueType, valueName) => valueType.Name == "Boolean" ? "bool" : GraphQlGeneratorConfiguration.DefaultScalarFieldTypeMapping(baseType, valueType, valueName);
```

**Comment by groege** [comment]
You are awesome!

**Comment by Husqvik** [comment]
https://www.nuget.org/packages/GraphQlClientGenerator/0.4.4

**Comment by groege** [comment]
Very awesome => though could you do the same thing for Guid?

**Comment by Husqvik** [comment]
If you use built-in `ID` type, that's handled already

```csharp
GraphQlGeneratorConfiguration.BooleanType = BooleanType.Custom;
GraphQlGeneratorConfiguration.IdType = IdType.Custom;

GraphQlGeneratorConfiguration.CustomScalarFieldTypeMapping =
    (baseType, valueType, valueName) =>
        valueType.Name switch
         {
             "Boolean" => "bool",
             "ID" => "Guid",
              _ => GraphQlGeneratorConfiguration.DefaultScalarFieldTypeMapping(baseType, valueType, valueName)
        };
````

**Comment by groege** [comment]
I just realized that this is caused by something else ==> "Kind" is always null (even though it should be "NON_NULL" for non null types (according to the UnwrapIfNonNull implementation).

graphQlType.Kind == GraphQlGenerator.GraphQlTypeKindNonNull ? graphQlType.OfType : graphQlType;

Problem is that the type is always SCALAR and never NON_NULL ==> and OfType is always null.
Therefore I cannot be sure if the column is marked as non nullable or not.

This is true as well for int/float,...

(Im using a separate Guid type not Id)

**Comment by Husqvik** [comment]
Yeah, the issue is I send already unwrapped type into the custom handler. Will have to change to send the raw one.

**Comment by Husqvik** [comment]
Pushed an update, could you test it out before I make a new nuget package?

**Comment by groege** [comment]
Will clone the repo now ;)

**Comment by groege** [comment]
I would make those public so one can use them:
```
        internal const string GraphQlTypeKindObject = "OBJECT";
        internal const string GraphQlTypeKindEnum = "ENUM";
        internal const string GraphQlTypeKindScalar = "SCALAR";
        internal const string GraphQlTypeKindList = "LIST";
        internal const string GraphQlTypeKindNonNull = "NON_NULL";
        internal const string GraphQlTypeKindInputObject = "INPUT_OBJECT";
        internal const string GraphQlTypeKindUnion = "UNION";
        internal const string GraphQlTypeKindInterface = "INTERFACE";
```
Or replace them with a public enum.  (I think that would be better than to check with "NON_NULL" directly)

I've also added:
```
if (valueType is GraphQlFieldType fieldType && fieldType.Kind == "NON_NULL")
    {
        valueType = fieldType.UnwrapIfNonNull();
        if(valueType.Kind == "ENUM")
        {
            return valueType.Name;
        }
```
Weird thing is I get only two of many enums if I set the break point on the return and all enums remain nullable.

I guess it only works if the enum is within a list?:
```
    public ICollection<FhpStorage> Storage
    {
        get { return (ICollection<FhpStorage>)_storage.Value; }
        set { _storage = new InputPropertyInfo { Name = "storage", Value = value }; }
    }
    public ICollection<FhpTransportOrderStatusId> StatusIds
    {
        get { return (ICollection<FhpTransportOrderStatusId>)_statusIds.Value; }
        set { _statusIds = new InputPropertyInfo { Name = "statusIds", Value = value }; }
    }
```
Would be awesome if that were possible with other Enums as well.

**Comment by groege** [comment]
Man you are awesome ==> even faster than I can edit my comment ^^
What do you think about my last edit on the very bottom about being able to see if a property has been loaded even when it is null?

**Comment by Husqvik** [comment]
The nullability of all members in data classes is intentional, as you can query any subset of fields so default values can lead to very misleading result. With booleans I understand that `null` is very often treated as false but I prefer to use the customization handler for such manipulation.

I like the plain classes as they are more. What I can do is to add another extension point where you can write own implementation of getters and setters. Plus maybe an option to use auto properties like now or backing fields.

**Comment by groege** [comment]
> I like the plain classes as they are more. What I can do is to add another extension point where you can write own implementation of getters and setters. Plus maybe an option to use auto properties like now or backing fields.

Sounds awesome to me.

Can you also give me the option to make Enums non nullable?

**Comment by Husqvik** [comment]
This should make the trick:

```csharp
GraphQlGeneratorConfiguration.CustomScalarFieldTypeMapping =
	(baseType, valueType, valueName) =>
	{
		var isNotNull = valueType.Kind == GraphQlTypeKind.NonNull;
		var unwrappedType = valueType is GraphQlFieldType fieldType ? fieldType.UnwrapIfNonNull() : valueType;
		return isNotNull && unwrappedType.Kind == GraphQlTypeKind.Enum ? unwrappedType.Name : GraphQlGeneratorConfiguration.DefaultScalarFieldTypeMapping(baseType, valueType, valueName);
	};
```

**Comment by groege** [comment]
> ```cs
> var isNotNull = valueType.Kind == GraphQlTypeKind.NonNull;
> 		var unwrappedType = valueType is GraphQlFieldType fieldType ? fieldType.UnwrapIfNonNull() : valueType;
> 		return isNotNull && unwrappedType.Kind == GraphQlTypeKind.Enum ? unwrappedType.Name : GraphQlGeneratorConfiguration.DefaultScalarFieldTypeMapping(baseType, valueType, valueName);
> ```

I've copied your code, but it doesn't work.

**Comment by groege** [comment]
Thanks it is working!
I think it's ready for a new nuget package ;)

**Comment by groege** [comment]
Also just for info as by definition "Float" is defined as 64 bit float which is double in c#.
Therefore I'd recommend to use double instead of decimal as default (Since i'm using my custom implementation it doesn't matter to be but I thought I'd mention it)

**Comment by Husqvik** [comment]
There is `FloatTypeMapping` to configure the types. In some cases I prefer to use decimal as there is no binary precision issues when using the members in math formulas.

**Comment by Husqvik** [comment]
a new nuget https://www.nuget.org/packages/GraphQlClientGenerator/0.4.5
