### ISSUE TITLE
Register as tool

### ISSUE THREAD

**Issue by acelot** [Husqvik/GraphQlClientGenerator#59]
It would be more convenient to use the generator as a dotnet tool:
```
dotnet tool install --global GraphQlClientGenerator
```

It's very simple to register GraphQlClientGenerator as tool https://medium.com/@bilalfazlani/net-core-local-tools-are-here-fe9ac2464481

**Comment by Husqvik** [comment]
fixed `dotnet tool install GraphQlClientGenerator.Tool --global`
