### ISSUE TITLE
Doesn't generate correctly the builder

### ISSUE THREAD

**Issue by CyrilleFormont** [Husqvik/GraphQlClientGenerator#6]
Hi,

Just facing the issue because my schema take as an input a list of something, but the generated builder doesn't take anything as the parameters except the return type.

Here is my schema :
`addDiariesOrUpdate(userDiaries: [UserDiaryInput]!): [UserDiaryType]
`
Here is the generated code : 
```
WithAddDiariesOrUpdate(
      UserDiaryTypeQueryBuilder userDiaryTypeQueryBuilder)
    {
      return this.WithObjectField("addDiariesOrUpdate", (GraphQlQueryBuilder) userDiaryTypeQueryBuilder, (IDictionary<string, object>) null);
    }
```

Known issue ?

**Comment by Husqvik** [comment]
Hi, this project is very simplistic and by far doesn't support all GraphQL features. I assume your GraphQL API is not public so I can't simply access it and use it to add the missing implementation. If not, would it be possible to give me the schema metadata, then I'm able to generate the classes myself and hopefully fix the issue without the API access.

**Comment by NikitaG** [comment]
Hi,

I have same issue. I fixed it by changing BaseClasses template. 
Add to BuildArgumentValue function:
```		
if (value is IEnumerable<GraphQlMutationInput> enumerable)
        return $"[{string.Join(",", enumerable.Select(item => item.Build(formatting, level + 2, indentationSize)))}]";
   ```
