### ISSUE TITLE
Nullable reference type issue

### ISSUE THREAD

**Issue by bddckr** [Husqvik/GraphQlClientGenerator#61]
I'm getting CS8601 warnings/errors in generated output due to this:
https://github.com/Husqvik/GraphQlClientGenerator/blob/2e28c3ac304031bd295b9c6b9faee5d6a50b0a44/src/GraphQlClientGenerator/GraphQlGenerator.cs#L833
As a workaround I'm currently applying the following step after running the generator:
```c#
if (GraphQlGeneratorConfiguration.CSharpVersion == CSharpVersion.NewestWithNullableReferences)
{
    result = result.Replace("new GraphQlDirective[]", "new GraphQlDirective?[]", StringComparison.Ordinal);
}
```

I.e. the fix can either be to use `new GraphQlDirective?[]`, or alternatively, just `new []` actually. Maybe even just `{ ... }`... See [this](https://stackoverflow.com/a/5678244/283482).

**Comment by Husqvik** [comment]
neither `new []` nor `{ ... }` can be used. `new []` works only with implicitly convertible types and `{ ... }` only with fields.

**Comment by bddckr** [comment]
Oh I see! Thanks for the quick fix again! ❤️
