### ISSUE TITLE
GraphQlGeneratorConfiguration.DefaultScalarFieldTypeMapping should be static

### ISSUE THREAD

**Issue by bddckr** [Husqvik/GraphQlClientGenerator#63]
The Readme still says it is, but it looks like the recent change to move to instances for the generator API did change this API, too.

`GraphQlGeneratorConfiguration.DefaultScalarFieldTypeMapping` does not seem to use any instance members.

If this is intended the Readme needs an update.

**Comment by Husqvik** [comment]
I actually does - `GraphQlGenerator.AddQuestionMarkIfNullableReferencesEnabled(this, dataType)`. It's needed to resolve the nullable references. I haven't landed on a final solution yet but for now `DefaultScalarFieldTypeMapping` will be instance method.

**Comment by bddckr** [comment]
Shows that I only read this on GitHub without spinning up my IDE 🙈

Thanks for the docs update ❤️
