### ISSUE TITLE
An error occured: Index was outside the bounds of the array.

### ISSUE THREAD

**Issue by AndiRudi** [Husqvik/GraphQlClientGenerator#66]
I wanted to check out the GraphQlClient Generator but got the error
`An error occured: Index was outside the bounds of the array.`

I used it like that
```
graphql-client-generator --serviceUrl http://inventory-api.sandbox.one.fit/v1/graphql --outputPath test --namespace test
```

Did I do it wrong or is in application error? Is there a possibility to get more detailed error message? Let me know If I can help.

**Comment by Husqvik** [comment]
Updated packages are published now. Version 0.7.2. Also included full exception text as the error message.
