### ISSUE TITLE
Allow generation from a schema.json file

### ISSUE THREAD

**Issue by Kurren123** [Husqvik/GraphQlClientGenerator#67]
I'm writing a GraphQL api which is not intended to be a web service, so there will be no service url. I can however generate a schema.json file, will it be possible to pass this file in as an argument rather than the service url?

Thanks

**Comment by Husqvik** [comment]
Pushed also nuget tool update: https://www.nuget.org/packages/GraphQlClientGenerator.Tool/0.7.2.1

**Comment by Husqvik** [comment]
`--serviceUrl` is optional now. Schema file can be specified using `--schemaFileName Path/To/GqlSchemaFile.json`
