### ISSUE TITLE
Configurable NamingHelper

### ISSUE THREAD

**Issue by v-braun** [Husqvik/GraphQlClientGenerator#68]
We serialize the generated model by ourself with JSON.NET and saw that during the class generation a ```NamingHelper``` is used with a static ToPascalCase implementation.

We have a lot of properties with (abbreviations) uppercase letters and this will be generated lowercase generated.

**Comment by Husqvik** [comment]
Not sure if I follow. Are we talking about generating the GraphQL query and/or its parameters or mapping resulting JSON into classes and their properties.

**Comment by v-braun** [comment]
Sorry for the confusion!

We use the Lib to generate Models for our API and in most cases we also use the QueryBuilder to create queries based on the generated models, wich is fine.

Unfortunatley the current embed variables within the query and we have one specific case where we want to send a query with variables by side. For that we 
- created a query as a string 
- tried to serialize (JSON.NET) only the models
- put the serialized json into the ```variables``` section of our request
- fired the reques

This caused an error on the API side.  
Some of the property names (specially the ones that where written in uppercase letters like CM, EUR, PS, etc.) could not be mapped because the properties where generated PascalCase: Cm, Eur, Ps, etc. (see https://github.com/Husqvik/GraphQlClientGenerator/blob/d45424b84dafa8ae40852e282689046dd1aebe4b/src/GraphQlClientGenerator/GraphQlGenerator.cs#L571)

The information of the real name is still stored within the ```QueryBuilderParameter<T>``` classes and we saw that there is a custom JSON serializer annotated to each property, but we could not make the correct serialization working.

As a workaround we decided to create a custom JsonConverter:

``` cs
    public class GeneratedGraphDtoConverter: JsonConverter
    {
        public GeneratedGraphDtoConverter()
        {
        }

        public override bool CanRead { get { return false; } }

        public override bool CanConvert(System.Type objectType) {
            var result = typeof(IGraphQlInputObject).IsAssignableFrom(objectType);
            return result;
        }

        public override object ReadJson(JsonReader reader, System.Type objectType, object existingValue, JsonSerializer serializer)
        {
            throw new System.NotImplementedException();
        }

        public override void WriteJson(JsonWriter writer, object value, JsonSerializer serializer)
        {
            var obj = (IGraphQlInputObject)value;
            var jobj = new JObject();
            
            var props = obj.GetPropertyValues();
            writer.WriteStartObject();
            foreach(var prop in props){
                var name = prop.Name;
                var val = prop.Value as QueryBuilderParameter;

                if (val?.Value != null)
                {
                    writer.WritePropertyName(name);
                    serializer.Serialize(writer, val.Value);   
                }
            }
            writer.WriteEndObject();
        }
    }

```

We are using this converter to serialize the generated models.

To be clear: this is only needed in cases where you have to use the Models without using the QueryBuilder.

**Comment by Husqvik** [comment]
Did you try `JsonPropertyGeneration = JsonPropertyGenerationOption.CaseSensitive` for the configuration object which will generate `[JsonProperty("rawGraphQlFieldName")]` so the serialized field name will be exactly the same as the original GraphQL field name.

**Comment by earloc** [comment]
setting `JsonPropertyGeneration = JsonPropertyGenerationOption.CaseSensitive` would result in the following property:

```C#
        [JsonProperty("EUR")]
        [JsonConverter(typeof(QueryBuilderParameterConverter<string>))]
        public QueryBuilderParameter<string> Eur
        {
            get { return (QueryBuilderParameter<string>)_eur.Value; }
            set { _eur = new InputPropertyInfo { Name = "EUR", Value = value }; }
        }
```
@v-braun would this be sufficient? this should serialise as **EUR**, rather than **Eur**.

**Comment by Husqvik** [comment]
yes

**Comment by v-braun** [comment]
@earloc sounds good! Perfect 🎉
