### ISSUE TITLE
Documentation for usage and return cast

### ISSUE THREAD

**Issue by AndiRudi** [Husqvik/GraphQlClientGenerator#70]
I am trying to figure out how to send the generated query (using https://github.com/graphql-dotnet/graphql-client) but I am stuck at the return cast. It would be great to have an example on how to use the generated query or mutation and also how to pass back the results into the generated classes.

In the following code sample I can alread send the query but what do I specify as `T` to have the results in correct form?
```
var query = builder.Build(Formatting.Indented);
var request = new GraphQLHttpRequest(...) { Query = query };
await _graphQLClient.SendMutationAsync<T>(request);
```

Thanks for any advice

**Comment by Husqvik** [comment]
One of the generated sections is named `# data classes`. The first class is the root response object, very often called "Query" or "Mutation" depending what kind of request is issued. It might be very misleading but the names are generated from the schema metadata. So just use one of them as the generic type of the `SendQueryAsync` method: `var graphQLResponse = await graphQLClient.SendQueryAsync<Query>(request);`

Here is working example using Tibber API:

you need to use
```csharp
configuration.CustomClassNameMapping.Add("Consumption", "ConsumptionEntry");
configuration.CustomClassNameMapping.Add("Production", "ProductionEntry");
```

or rename the classes manually as the types have properties of the same name which is not allowed in C#.

```csharp
var graphQLClient = new GraphQLHttpClient("https://api.tibber.com/v1-beta/gql", new NewtonsoftJsonSerializer());

graphQLClient.HttpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", "d1007ead2dc84a2b82f0de19451c5fb22112f7ae11d19bf2bedb224a003ff74a");

var queryBuilder =
    new QueryQueryBuilder()
        .WithAllScalarFields()
        .WithViewer(
            new ViewerQueryBuilder()
                .WithHome(
                    new HomeQueryBuilder()
                        .WithConsumption(
                            new HomeConsumptionConnectionQueryBuilder().WithNodes(new ConsumptionEntryQueryBuilder().WithAllFields()),
                            EnergyResolution.Monthly,
                            last: 12),
                    Guid.Parse("c70dcbe5-4485-4821-933d-a8a86452737b")
                )
        );

var request = new GraphQLRequest { Query = queryBuilder.Build(Formatting.Indented) };

var graphQLResponse = await graphQLClient.SendQueryAsync<Query>(request);

var monthlyEntries = graphQLResponse.Data.Viewer.Home.Consumption.Nodes;
```

**Comment by AndiRudi** [comment]
That works. Thanks!
