### ISSUE TITLE
Namespaces with dots not accepted

### ISSUE THREAD

**Issue by imdbere** [Husqvik/GraphQlClientGenerator#72]
First of all, great project!

I use the C#9 source generator and it works really well for the most part.
One problem i stumbled upon is that the GraphQlClientGenerator_Namespace property does not accept namespaces with dots in them, so e.g. 'MyNamespace.GraphQl' would not work.

I tracked this problem to the CSharpHelper.IsValidIdentifier method that seems to not accept dots because UnicodeCategory.OtherPunctuation is not present in the switch statement. I think simply adding it would make this work.

Thanks !

**Comment by Husqvik** [comment]
forgotten about that :). I'll make fix hopefully during today.

**Comment by Husqvik** [comment]
soon available https://www.nuget.org/packages/GraphQlClientGenerator/0.8.1
