### ISSUE TITLE
Double parameter names in With<Type> methods

### ISSUE THREAD

**Issue by sanne-at-visual-nl** [Husqvik/GraphQlClientGenerator#74]
We have an issue with the generation of the With... methods. In these methods the generator adds some extra parameters (e.g. alias, include, skip). But our GraphQL partner has used the same parameter name ('skip') as an argument in their API. This results in a duplicate parameter name. Should the generator not check for duplicate names?

Thank you for creating this tool.

**Comment by Husqvik** [comment]
Didn't consider that :), I'll make fix for that.
