### ISSUE TITLE
Missing case sensitive type names

### ISSUE THREAD

**Issue by sanne-at-visual-nl** [Husqvik/GraphQlClientGenerator#75]
Input type names are sometimes needed when you use variables declared inside the query. Does the generator have an option to return the case sensitive schema name of a type without the Pascal casing? We rather use nameof() or something similar, and not a magic string.

**Comment by Husqvik** [comment]
did you try `configuration.JsonPropertyGeneration = JsonPropertyGenerationOption.CaseSensitive` or `JsonPropertyGenerationOption.Always`

the all the data properties will get the attribute that ensures exactly same names as the schema has.

**Comment by sanne-at-visual-nl** [comment]
We did, but the fields don't use the type name as name. I'll give an example. We need to use a PersonIDInput type. This will generate a PersonIdInput class.
```
type PersonIDInput {
  identifier: String!
  type: PersonIDEnum!
}
```
We can use 3 methods to pass the argument:
1. as variable (outside)
```
query ($id: PersonIDInput!) {
  person (id: $id) { lastname }
}
{
  "id": { "identifier": "********", "type": "ID" }
}
```
2. as variable (inside)
```
query ($id: PersonIDInput = { identifier: "********", type: ID }) {
  person (id: $id) { lastname }
}
```
3. inline (inside)
```
query {
  person (id: { identifier: "********", type: ID }) { lastname }
}
```
In both case 1 and 2, you need to add the type name to the query. This case sensitive name is not available in de generated classes. We could opt to always use case 3 because it doesn't require a type name, but we think that is not a good practice.

**Comment by Husqvik** [comment]
Aha, I misunderstood, thought that it's about the property names, not type names.

I'll add generation of a constant to every input object class.

Then next potential next step it could be automatically generate the type name when query parameter created with the type so there is no need to pass it manually.

**Comment by sanne-at-visual-nl** [comment]
Thank you for your quick reaction. That last part is indeed the preferred way.

**Comment by Husqvik** [comment]
added `GraphQlTypeName` class containing all the type names as constants.

Also added `public GraphQlQueryParameter(string name, T value, bool isNullable = true)` constructor that resolves built-in scaler types and the input object types automatically. I still plan to work on that. The old constructor remains because input type can be arrays or nested arrays of not nullable types that most likely cannot be ever resolved automatically.
