### ISSUE TITLE
Deep Mutations

### ISSUE THREAD

**Issue by Chaosflo** [Husqvik/GraphQlClientGenerator#76]
Hello,

Do you have ideas how I can solve this problem? 

In my company we need a mutation who can update a set of multilevel deep propertys.
Here is what I mean!

To save privacy I created a fictional example

![grafik](https://user-images.githubusercontent.com/13841355/101779260-53aa4b80-3af5-11eb-8852-0320049d6e74.png)

What we want to do is to update propertys of the let's say the **Lock** node within the mutation of the **SmartHomeController** node.

In the structure your lib created I cant do this because of the generated **Ref** classes, the propertys I need are not generated for a reason. Can you clearify the reason? 

Here is link who describes the topic too => [Click Me!](https://dgraph.io/docs/graphql/mutations/deep/)

Thanks for your attention, see ya soon =)

**Comment by Husqvik** [comment]
Can you provide GraphQL schema in json? So I have real example to test/debug on.
If the bubbles in your diagram represents input object types the deep mutations should be working,

**Comment by Chaosflo** [comment]
[Schema.zip](https://github.com/Husqvik/GraphQlClientGenerator/files/5677618/Schema.zip)

I hope it is what you need! 
I used your introspection query to generate the json

**Comment by Husqvik** [comment]
Yes, thank you. I'll look at it during the weekend.

**Comment by Husqvik** [comment]
Are you querying any field from the updated node?

```csharp
new MutationQueryBuilder()
    .WithUpdateLock(
        new UpdateLockPayloadQueryBuilder().WithNumUids(),
        new UpdateLockInput
        {
            Set = new LockPatch { Code = "1234", Nodes = new NodeRef { NodeId = Guid.NewGuid() } }
        })
    .Build(Formatting.Indented)
```

generates

```gql
mutation {
  updateLock(input: {
      set: {
          Nodes: {
              Node_ID: "3c62a557-d6ba-44d8-b142-021d98a8d503"
            }
          Code: "1234"
        }
    }) {
    numUids
  }
}
```

but without querying for `WithNumUids()` the result is just

```gql
mutation {

}
```

is this the issue?

**Comment by Chaosflo** [comment]
Hello again!

No, thats not my problem.
My problem are the input objects.

`new MutationQueryBuilder()
    .WithUpdateLock(
        new UpdateLockPayloadQueryBuilder().WithNumUids(),
        new UpdateLockInput
        {
            Set = new LockPatch { Code = "1234", Nodes = new **NodeRef** { NodeId = Guid.NewGuid() } }
        })
    .Build(Formatting.Indented)`

I cant go any further than 2 levels. Lock properties => Node properties => Node properties => Node properties => ... => ...

What I want is to update from house all nodes beneath it for example.

**Comment by Husqvik** [comment]
`NodeRef` has only single scalar field. So it cannot contain any nested object. The object types are completely separated and independent from input types and input types cannot inherit from any type.

Could you post an example for the mutation query? Still don't get how the GraphQL can even accept it when input object don't define the nesting.

**Comment by Chaosflo** [comment]
Thanks for fast answering! 

I understand now how this is working out 

I thought you were generating it by yourself but you dont take all from the schema.

I will report that back to my lead.

**Comment by Chaosflo** [comment]
Thanks for fast answering! 

I understand now how this is working out 

I thought you were generating it by yourself but you dont take all from the schema.

I will report that back to my lead.

**Comment by Husqvik** [comment]
Yes. Everything is taken from the schema. I'm still interested about the mutation query, as you would be sending something not compliant with the schema which should be rejected by GraphQL server.

**Comment by Chaosflo** [comment]
Hey, 

I tried a bit around and got on the next behaviour I dont understand. 
Can you explain me why the generator is generating this 
![grafik](https://user-images.githubusercontent.com/13841355/102466089-cca62780-404e-11eb-9b72-924aa3619b5e.png)

_It is the same schema as before_ 

It generates an Interface with **INode** and a normal class with **Node**.
But it uses the normal class for updating, querying and so on.
Why does this strange behaviour happen? 

Here a few examples =>
![grafik](https://user-images.githubusercontent.com/13841355/102466496-62da4d80-404f-11eb-9c98-fcdab92dc321.png)
Here is the data class where I need the interface that I can query what I want from the database => Door and so on

![grafik](https://user-images.githubusercontent.com/13841355/102466618-8ac9b100-404f-11eb-8a12-70fc72ace42f.png)
Here the selected line would be nice if I could receive the interface not the class

If you need more examples let me know! 

Thanks for your patience
See you soon 
Greetings

**Comment by Husqvik** [comment]
Currently the data class generation/deserialization is not so smart. When an object is returned as interface the actual type can be resolved only in runtime not at generation time. So for now I just generate dummy class with the same name as interface containing only interface field. Proper way would be to make JsonConverter that would handle the concrete type while deserializing. I'll try to implement that but it will take some time.

**Comment by Chaosflo** [comment]
Thank you!

We will waiting for this feature.

Maybe I will get some private time to help you, if you want this. 
I think it's not a big topic to implement but I don't know the complexity of your code.

Greetings!

**Comment by Chaosflo** [comment]
Just to inform you! 
I started to investigating what must be changed!

What I have done now is to delete this dummy type in the generation. The generated Code is now clean of this dummy type.
Now I am investigating how to do the same with the ref type

**Comment by Chaosflo** [comment]
I am sry to send it via ZIP but I am not able to create a new branch to checkIn =/ 

Here are my changes! 
In the Command Line Tool Program.cs is my testing stage.
I had to add the typenames property everywhere. 

Feel free to ask me anything! 
Have a nice day =) 
[FeatureInterface.zip](https://github.com/Husqvik/GraphQlClientGenerator/files/5715347/FeatureInterface.zip)

**Comment by Husqvik** [comment]
New Nuget is available now. Thanks for the effort. It's good approach. I just used explicit attributes instead of lax matching type names and also added support for collections of interface types.
