### ISSUE TITLE
GRAPHQLGEN1000 error when referencing a project that uses GraphQlClientGenerator

### ISSUE THREAD

**Issue by imdbere** [Husqvik/GraphQlClientGenerator#77]
Hi,
I came across a problem when using GraphQlClientGenerator across multiple projects that reference each other.
I have a library project that references the GraphQlClientGenerator source generator to generate source files from a schema.json file, this works fine. The problem arises when creating a second projects that references the first library project. When trying to build it, i get this error:
`GRAPHQLGEN1000: Either "GraphQlClientGenerator_ServiceUrl" parameter or GraphQL JSON schema additional file must be specified.`

Now, I could copy the schema.json file to this second project and add the GraphQlClientGenerator_ServiceUrl but this would kind of defeat the purpose of having a single library project and it would also mean that I have to do this for each project that references the first one.

I think the problem is that the GraphQlClientGenerator analyzer is added as a dependency to all projects which reference a project with the analyzer added, which causes the source generator to run when it shouldn't.
Do you think this is fixable or can you think of any workaround ?

Thanks !

**Comment by Husqvik** [comment]
So even with `IncludeAssets="analyzers"` - `<PackageReference Include="GraphQlClientGenerator" Version="0.8.*" IncludeAssets="analyzers" />` a project that refers the project with the GraphQlClientGenerator package tries to generate basically second instance of the client in it? That is not intended of course. Need to check it out.

**Comment by Husqvik** [comment]
Meanwhile try to play around with `<ExcludeAssets>analyzers,compile</ExcludeAssets>` or similar in the parent project

**Comment by imdbere** [comment]
I tried to add this to the parent project, with no success, the analyzer seems to be still there
```
<ProjectReference Include="...">
   <ExcludeAssets>analyzers,compile</ExcludeAssets>
</ProjectReference>
```

**Comment by imdbere** [comment]
I think `<ExcludeAssets>` may only be available in NuGet package references and not in project references

**Comment by Husqvik** [comment]
Temporary solution could be adding this snippet to the parent project file.

```xml
<Target Name="DisableAnalyzers" BeforeTargets="CoreCompile">
  <ItemGroup>
    <Analyzer Remove="@(Analyzer)" />
  </ItemGroup>
</Target>
```

But it will disable all analyzers, not just the client generator. Don't know how to make that conditional on analyzer name.

**Comment by imdbere** [comment]
That seems to work as a temporary fix, thanks 👍

**Comment by Husqvik** [comment]
Seems to be simpler than that. Just mark the generator assets as private:

`<PackageReference Include="GraphQlClientGenerator" Version="0.8.*" IncludeAssets="analyzers" PrivateAssets="all" />`

**Comment by SimonCropp** [comment]
@Husqvik `IncludeAssets="analyzers" PrivateAssets="all"` doesnt seem to work for me. i still get 

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	GRAPHQLGEN1000	Either "GraphQlClientGenerator_ServiceUrl" parameter or GraphQL JSON schema additional file must be specified.	Tests	C:\Code\ElectorateReportingApi\src\Tests\CSC	1	
```

**Comment by Husqvik** [comment]
Do refer the `GraphQlClientGenerator` package only from single project or from multiple? Could you post the project structure (project referring to `GraphQlClientGenerator` and the dependencies until the one that fails to build) so I can try to replicate the case.

**Comment by SimonCropp** [comment]
@Husqvik seems to only happen when `<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>` is applied

https://github.com/SimonCropp/GraphQlClientGeneratorRepo

**Comment by SimonCropp** [comment]
> Do refer the GraphQlClientGenerator package only from single project or from multiple

single project

and i found a workaround: https://stackoverflow.com/a/66130446/53158

**Comment by SimonCropp** [comment]
actually still fails without CopyLocalLockFileAssemblies. i pushed an update

**Comment by Husqvik** [comment]
Ok `PrivateAssets="all"` is to disable inheritance of package to dependent projects. But it's really weird the `ExcludeAssets` does not work. Ok I will change the analyzer to just terminate gracefully if no configuration option is set instead of an error.

**Comment by SimonCropp** [comment]
> Ok I will change the analyzer to just terminate gracefully if no configuration option is set instead of an error

sounds good.

Although I would prefer that the lib and source generator were split into different packages

**Comment by Husqvik** [comment]
this one works
```xml
<Target Name="DisableAnalyzers" BeforeTargets="CoreCompile">
    <ItemGroup>
      <Analyzer Remove="@(Analyzer)" Condition="'%(Filename)' == 'GraphQlClientGenerator'"/>
    </ItemGroup>
  </Target>
```

**Comment by Husqvik** [comment]
Btw. why do you want to use manual generation instead of source generator?

**Comment by SimonCropp** [comment]
@Husqvik yep. I assume you got that from my stackoverflow answer. but it is a pretty big hammer for people to use so they can consumer this project as a library

**Comment by Husqvik** [comment]
Yes, didn't know the exclusion doesn't work.

**Comment by SimonCropp** [comment]
> Btw. why do you want to use manual generation instead of source generator?

we own the graphql service. so as part of the tests, we spin up an instance of the graphql service and gen a client proxy to be consumed by clients.

**Comment by Husqvik** [comment]
new nuget https://www.nuget.org/packages/GraphQlClientGenerator/0.9.3

**Comment by SimonCropp** [comment]
works perfectly. thanks for the quick turn around
