### ISSUE TITLE
Override mapping of non-custom scalar types

### ISSUE THREAD

**Issue by imdbere** [Husqvik/GraphQlClientGenerator#78]
Hi,
Is there a way to map certain standard GraphQL types to different .NET types, like it is possible with custom scalar types ?
For example i would like to map the GraphQL 'ID' type to the .NET 'string' or 'uint', but it seems like specifying this in the RegexScalarFieldTypeMappingProviderConfiguration.json doesn't do anything.
Thanks!

**Comment by Husqvik** [comment]
There is configuration property for every built-in type, `IdTypeMapping` for example. Check `GraphQlGeneratorConfiguration` properties.

```csharp
public enum IdTypeMapping
{
    Guid,
    String,
    Object,
    Custom
}
```

`Custom` value will pass the generation through the `ScalarFieldTypeMappingProvider`.
