### ISSUE TITLE
Can not compile generated code

### ISSUE THREAD

**Issue by sfiodorov** [Husqvik/GraphQlClientGenerator#82]
Hey.
Thats for such usefull lib.
Generated code fails to compile becouse of:
`if (valueType.IsAssignableTo(typeof(IEnumerable)))`
For now, im just replacing it with IsAssignableFrom and reversing the order.
Looks like it is new and exist for dotnet 5. Any chance to replace it with IsAssignableFrom , so code can be used from dotnet 3 ?
Thanks!

**Comment by Husqvik** [comment]
what is your compilation target? For netstandard < 2.0 `IsAssignableTo` most likely cannot be called directly on type but an extension method `GetTypeInfo()` must be called first. Is it so?

**Comment by Husqvik** [comment]
didn't realize that `IsAssignableTo` is so new, will use the `IsAssignableFrom` to make it more compatible. Thanks for pointing out.

**Comment by Husqvik** [comment]
Do you need a new Nuget?

**Comment by sfiodorov** [comment]
Thanks for fix.
Not critical for now, but will be nice to get fixed version in reasonable time.
Thanks again for quick response.
