### ISSUE TITLE
Missing known types

### ISSUE THREAD

**Issue by CyrilleFormont** [Husqvik/GraphQlClientGenerator#9]
```
case "Decimal":
     propertyType = "decimal?";
     break;
case "DateTime":
case "Date":
     propertyType = "DateTime?";
`break;`

```

**Comment by Husqvik** [comment]
`Date` and `DateTime` are not built-in types it's most likely custom scalar types defined by your service. There is `GraphQlGeneratorConfiguration.CustomScalarFieldTypeMapping` fuction that can be used for custom GraphQlType -> .NET type implementation but currently it's invoked only on string type. We should probably change it to be invoked also on any other non-built in scalar type.
