### ISSUE TITLE
Error CS0738 when compiling generated classes and interfaces

### ISSUE THREAD

**Issue by mhryshkin** [Husqvik/GraphQlClientGenerator#90]
Hey there! I've found this library really useful.
Facing C# compiler errors when dealing with GraphQL schema which contains interfaces.
The generated classes and interfaces: [net fiddle example](https://dotnetfiddle.net/r5pf5M).
I guess variance in generic interfaces of C# would help to resolve it if the generated interfaces were generic

**Comment by Husqvik** [comment]
could you post the GraphQL schema metadata so I can generate the classes to replicate the problem?

**Comment by mhryshkin** [comment]
@Husqvik Does this work for you?

`"""
The `JSONObject` scalar type represents JSON objects as specified by [ECMA-404](http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-404.pdf).
"""
scalar JSONObject

interface ItemOutputInterface {
  rows: JSONObject!
}

interface ColumnOutputInterface {
  name: String!
}

interface TableOutputInterface {
  columns: [ColumnOutputInterface!]!
  rows: [ItemOutputInterface!]!
}

type ColumnOutput implements ColumnOutputInterface {
  name: String!
}

interface TableOutputInterface {
  columns: [ColumnOutputInterface!]!
  rows: [ItemOutputInterface!]!
}

type ConcreteItemOutput implements ItemOutputInterface {
  rows: JSONObject!
}

type ConcreteTableOutput implements TableOutputInterface {
  columns: [ColumnOutput!]!
  rows: [ConcreteItemOutput!]!
}
`

**Comment by Husqvik** [comment]
could you generate the JSON version using

```graphql
query IntrospectionQuery {
    __schema {
      queryType { name }
      mutationType { name }
      subscriptionType { name }
      types {
        ...FullType
      }
      directives {
        name
        description
        locations
        args {
          ...InputValue
        }
      }
    }
  }

  fragment FullType on __Type {
    kind
    name
    description
    fields(includeDeprecated: true) {
      name
      description
      args {
        ...InputValue
      }
      type {
        ...TypeRef
      }
      isDeprecated
      deprecationReason
    }
    inputFields {
      ...InputValue
    }
    interfaces {
      ...TypeRef
    }
    enumValues(includeDeprecated: true) {
      name
      description
      isDeprecated
      deprecationReason
    }
    possibleTypes {
      ...TypeRef
    }
  }

  fragment InputValue on __InputValue {
    name
    description
    type { ...TypeRef }
    defaultValue
  }

  fragment TypeRef on __Type {
    kind
    name
    ofType {
      kind
      name
      ofType {
        kind
        name
        ofType {
          kind
          name
            ofType {
            kind
            name
            ofType {
              kind
              name
              ofType {
                kind
                name
              }
            }
          }
        }
      }
    }
  }
```

It's much easier to work with.
