### ISSUE TITLE
Case sensitivity collision in schema

### ISSUE THREAD

**Issue by mveselov-de** [Husqvik/GraphQlClientGenerator#93]
My schema has the following type

```
type Version {
  version: String
  hash: String!
  build_time: String!
}
```

That is valid, since GraphQL is case sensitive. C# is not, so this leads to

`error CS0542: 'Version': member names cannot be the same as their enclosing type`

Although I personally think that is bad style, it is still valid and in my case I cannot influence the schema, unfortunately.

**Comment by Husqvik** [comment]
There is an option to handle such cases

`--classMapping             Format: {GraphQlTypeName}:{C#ClassName}; allows to define custom class names for specific GraphQL types; common reason for this is to avoid property of the same name as its parent class`

if you use code to generate  then

```csharp
var configuration = new GraphQlGeneratorConfiguration();
configuration.CustomClassNameMapping.Add("Version", "VersionType");
```
