### ISSUE TITLE
How to consume arrays of arrays

### ISSUE THREAD

**Issue by mveselov-de** [Husqvik/GraphQlClientGenerator#94]
Sorry to raise an issue for this, but I couldn't find any other way to contact you.

In my schema I have a simple query that returns the following -  [[Object!]!]!

In the autogenerated code this is represented by the following

```
 public class Query
    {
     public IList<IList<ObjectX>> ObjectXQuery { get; set; }
     }

```
That is the only place outside of QueryBuilder where this is referenced. I cannot figure out how to correctly consume this reply. Here is what I've used (it works fine with normal types)

```
 static void Main(string[] input_args)
        {
          //Building the list
           var test_data=GetResult().Result;
            }

 static async Task<IList<IList<ObjectX>>> GetResult()
        {
            var graphQLClient = new GraphQLHttpClient("http://localhost:9999/graphql", new NewtonsoftJsonSerializer());
            var test_query = new GraphQLRequest
            {
                Query = @"here goes the query"
                
                 };
            var test_result = await graphQLClient.SendQueryAsync<IList<IList<ObjectX>>>(test_query);
            return test_result.Data;
        }

```
This fails at runtime with the following

>  Innermost exception 	 Newtonsoft.Json.JsonSerializationException : Cannot deserialize the current JSON object (e.g. {"name":"value"}) into type 'System.Collections.Generic.IList`1[System.Collections.Generic.IList`1[]]' because the type requires a JSON array (e.g. [1,2,3]) to deserialize correctly.
> To fix this error either change the JSON to a JSON array (e.g. [1,2,3]) or change the deserialized type so that it is a normal .NET type (e.g. not a primitive type like integer, not a collection type like an array or List<T>) that can be deserialized from a JSON object. JsonObjectAttribute can also be added to the type to force it to deserialize from a JSON object.
>

**Comment by Husqvik** [comment]
I believe you are missing the GraphQL root result in you returning type. GraphQL response usually look like:
```json
{
    "data": ...
    "errors": [...]
}
```

So classes like
```csharp

var test_result = await graphQLClient.SendQueryAsync<GraphQlResponse<IList<IList<ObjectX>>>>(test_query);

public class GraphQlResponse<TDataContract>
{
    public TDataContract Data { get; set; }
    public ICollection<QueryError> Errors { get; set; }
}

public class QueryError
{
    public string Message { get; set; }
    public ICollection<ErrorLocation> Locations { get; set; }
}

public class ErrorLocation
{
    public int Line { get; set; }
    public int Column { get; set; }
}
```

I don't know how your schema looks like but you can just return the resulting JSON as string to see what is the mapping issue and adjust your response classes.

**Comment by mveselov-de** [comment]
I think this is exactly the issue - there is no type for root result. E.g. most other queries returns specific types that are defined by generator as classes. But this particular query returns array of objects. The object has a class created by generator, but the array doesn't. Resulting JSON looks like this

```
{
    "data": {
      "ObjectXQuery": [
        [
          {
            "id": "317",          
            "hash": "f1c988d97938c85e"
          },
          {
            "id": "4454",
            "hash": "f1c988d97938c85e"
         }
        ],
        [
            {
              "id": "359",
              "hash": "9bc82a11e5365e37"
            },
            {
              "id": "4534",              
              "hash": "9bc82a11e5365e37"
            }
          ]
    ]
    }
}

```

**Comment by Husqvik** [comment]
Closing the issue then.
