### ISSUE TITLE
List of Not Null items

### ISSUE THREAD

**Issue by EfiNadell** [Husqvik/GraphQlClientGenerator#95]
About the GraphQlQueryParameter class which takes this "bool isNullable = true" argument, and it is working pretty well when you have any Not Null object,

But issue start when you need a List of Not Null objects.

When trying to Build with a List of Not Null objects, the "isNullable" argument won't help you.
because it affect only the Array/List type but not the "arrayItemType", and of course if you will flag the isNullable=false the result became wrong "[Object]!" instead of the "[Object!]" you wanted.

I'll demonstrate an example to explain myself, assuming you have define this GraphQL type in schema:

type MyObjectType 
{
_id: UUID!
name: String!
list: [String!]
}

and now you want to run this mutation :

mutation (  $myList: [String!] = ["string_A",  "string_B",  "string_C"]  ) 
{
  CreateMyObject(name: "myName", list: $myList) 
    {
  	 _id
   	 list
    }
}

The syntax to build it with C# GraphQlClientGenerator looks as below (and correct me If I wrong): 

string[] arr= {"string_A", "string_B",  "string_C"};

var param = new GraphQlQueryParameter<string[]>("myList", arr, false/true);// putting here false or true won't help you

var mutation =  new MutationQueryBuilder()
                    .WithCreateMyObject(
                        new MyObjectTypeQueryBuilder().WithAllFields(),
                       name:"myName",
                      list: param)
                    .WithParameter(param)
                    .Build();

So running this code will result this mutation string:
mutation (  $myList: [String]! = ["string_A",  "string_B",  "string_C"]  ) 
{
  CreateMyObject(name: "myName", list: $myList) 
    {
  	 _id
   	 list
    }
}

as you can see I can't get the "[String!]" part I wanted.

I think the issue could be fixed by widening this generated method:

 "private static string GetGraphQlTypeName(T value, bool isNullable)"

and changing it to take one more argument specifying if the item is nullable, 

I tested and it is solving the issue, I just added the "isItemNullable" argument to the method, and then when the code is returned the listItemType /arrayItemType  I changed the return line to check the isItemNullable argument, as you can see the code listed below:

public GraphQlQueryParameter(string name, T value, bool isNullable = true, bool isItemNullable = true) 
                                                           : base(name, GetGraphQlTypeName(value, isNullable, isItemNullable), value)
        {
        }

        private static string GetGraphQlTypeName(T value, bool isNullable, bool isItemNullable)
        {
            var graphQlTypeName = GetGraphQlTypeName(typeof(T), isItemNullable);
            if (!isNullable)
                graphQlTypeName += "!";

            return graphQlTypeName;
        }

        private static string GetGraphQlTypeName(Type valueType, bool isItemNullable)
        {
            valueType = Nullable.GetUnderlyingType(valueType) ?? valueType;

            if (valueType.IsArray)
            {
                var arrayItemType = GetGraphQlTypeName(valueType.GetElementType(), isItemNullable);
                return arrayItemType == null ? null : $"[{arrayItemType}{(isItemNullable ? string.Empty : "!")}]";
            }

            if (typeof(IEnumerable).IsAssignableFrom(valueType))
            {
                var genericArguments = valueType.GetGenericArguments();
                if (genericArguments.Length == 1)
                {
                    var listItemType = GetGraphQlTypeName(valueType.GetGenericArguments()[0], isItemNullable);
                    return listItemType == null ? null : $"[{listItemType}{(isItemNullable ? string.Empty : "!")}]";
                }
            }

and of course all the rest of the code stays as is without any changes.

I would like to hear what do you think about the issue and my suggestion above,
Thanks in advanced.

**Comment by Husqvik** [comment]
There is an overload allowing to specify GraphQL parameter type
```csharp
var param = new GraphQlQueryParameter<string[]>("myList", "[String!]", arr);
```

The problem with your solution is that it solves only very small subset of cases. The parameter type can be quite "wild", like
`[[String!]]` or even deeper nesting.

But based on your finding I fixed the resolution for primitive types represented in .NET as value types. `String` however is reference type.

**Comment by EfiNadell** [comment]
Thank you very much, 
I tried your suggestion with the overload (which I missed before) and now it is working perfect.
Thanks again.
