### ISSUE TITLE
Dynamic Object or JObject Support

### ISSUE THREAD

**Issue by Logic-Bits** [Husqvik/GraphQlClientGenerator#96]
Hi!

is it possible to have or pass dynamic objects?
I´m getting properties by a sql query and they could be changing or extending.
The generated classes dont have those new properties.

Thanks!

**Comment by Husqvik** [comment]
Hi. Sorry I didn't notice the request until now. Could you be more specific? GQL is strongly typed so there is no dynamic types. And custom scalars are still essentially strings, not objects.

**Comment by Husqvik** [comment]
You can use `scalar Dynamic` scalar value or anything that you don't map to concrete type, so you can pass any `object` for such value as parameter. In such case you can pass also `JObject`

**Comment by Logic-Bits** [comment]
Hi Husvik,

no problem. I also never saw that you answered.
My case is that I have a custom type (not scalar) with X customer properties.
Well for a customer we added custom field Y in addition to the others.
Now there is no way of getting that property without recompiling a special version for that customer.

Is there a solution for this problem? 
I would love to just get back the JObject with all the fields - or a way i can add that custom field Y on a customer config file.

Thanks in advance! Still using and loving your generator :)

**Comment by Husqvik** [comment]
the X customer properties you refer, you mean properties returned from the API. So just the data class properties. In that case you can simply add a partial class. Let say you have GraphQL type `MyData`. That get generated according to the GraphQL schema.
Then in addition to that you can create your separate file where you define your partial class:

```csharp
public partial class MyData
{
    public string MyCustomProperty1 { get; set; }

    // or you can include any json field not defined using following
    [JsonExtensionData]
    public IDictionary<string, object> Extensions { get; } = new Dictionary<string, object>(StringComparer.Ordinal);
}
```
